### ISSUE TITLE
recursive emacs errors on bad syntax

### ISSUE THREAD

**Issue by sam-s** [jorgenschaefer/elpy#1176] opened 2017-09-14 20:37 UTC
When I have unbalanced `"` in a python buffer, I land in `*Backtrace*` with no way out.
When I try to go back to the python buffer to fix the error, I am dropped back into the `*Backtrace*` almost immediately, so I have to jump very fast.
The backtrace is:
```
Debugger entered--Lisp error: (cl-assertion-failed ((> string-start last-string-end) "Overlapping strings detected" 10869 10869))
  cl--assertion-failed((> string-start last-string-end) "Overlapping strings detected" (10869 10869) nil)
  python-nav-end-of-statement()
  python-nav-end-of-defun()
  python-info-current-defun()
  run-hook-with-args-until-success(python-info-current-defun)
  which-function()
  which-func-update-1(#<window 290 on twitlib.py>)
  which-func-update()
  apply(which-func-update nil)
  timer-event-handler([t 0 0 500000 t which-func-update nil idle 0])
  recursive-edit()
  debug(error (cl-assertion-failed ((> string-start last-string-end) "Overlapping strings detected" 10869 10869)))
  cl--assertion-failed((> string-start last-string-end) "Overlapping strings detected" (10869 10869) nil)
  python-nav-end-of-statement()
  python-nav-end-of-defun()
  python-info-current-defun()
  #f(compiled-function (calltip) #<bytecode>)(nil)
  elpy-promise-resolve([*elpy-promise* #f(compiled-function (calltip) #<bytecode>) elpy-rpc--default-error-callback #<buffer twitlib.py> nil] nil)
  elpy-rpc--handle-json(((result) (id . 5333)))
  elpy-rpc--filter(#<process  *elpy-rpc [project:~/src/clear/algorithm/lib/ python:/Users/sds/.virtualenvs/algorisk/bin/python]*> "{\"result\": null, \"id\": 5333}\n")
  recursive-edit()
  debug(error (cl-assertion-failed ((> string-start last-string-end) "Overlapping strings detected" 10869 10869)))
  cl--assertion-failed((> string-start last-string-end) "Overlapping strings detected" (10869 10869) nil)
  python-nav-end-of-statement()
  python-nav-end-of-defun()
  python-info-current-defun()
  run-hook-with-args-until-success(python-info-current-defun)
  which-function()
  which-func-update-1(#<window 290 on twitlib.py>)
  which-func-update()
  apply(which-func-update nil)
  timer-event-handler([t 0 0 500000 t which-func-update nil idle 0])
  recursive-edit()
  debug(error (cl-assertion-failed ((> string-start last-string-end) "Overlapping strings detected" 10869 10869)))
  cl--assertion-failed((> string-start last-string-end) "Overlapping strings detected" (10869 10869) nil)
  python-nav-end-of-statement()
  python-nav-end-of-defun()
  python-info-current-defun()
  run-hook-with-args-until-success(python-info-current-defun)
  which-function()
  which-func-update-1(#<window 290 on twitlib.py>)
  which-func-update()
  apply(which-func-update nil)
  timer-event-handler([t 0 0 500000 t which-func-update nil idle 0])
```
as you can see, there are several nested `cl-assertion-failed`.
This does not happen when I disable `elpy`.

**Comment by jorgenschaefer** [comment] 2017-09-22 09:08
Hello, and thanks for the report! This looks like a bug in `which-function` together with python.el – can you reproduce this by just enabling `which-function-mode`?

**Comment by cpitclaudel** [comment] 2018-05-18 15:32
Yup, it doesn't require elpy here:

```
Debugger entered--Lisp error: (cl-assertion-failed ((> string-start last-string-end) "Overlapping strings detected (start=%d, last-end=%d)" 13829 13850))
  cl--assertion-failed((> string-start last-string-end) "Overlapping strings detected (start=%d, last-end=%d)" (13829 13850) nil)
  python-nav-end-of-statement()
  python-nav-end-of-defun()
  python-info-current-defun()
  run-hook-with-args-until-success(python-info-current-defun)
  which-function()
  which-func-update-1(#<window 988 on coqdomain.py>)
  which-func-update()
  apply(which-func-update nil)
  timer-event-handler([t 0 0 500000 t which-func-update nil idle 0])
```

**Comment by cpitclaudel** [comment] 2018-05-18 15:40
Here's a small repro, for the record:

```
def f(self):
    "

def g():
    """That's a docstring"""
    return ''
```

Putting the point after the unclosed quote yields this:

```
Debugger entered--Lisp error: (cl-assertion-failed ((> string-start last-string-end) "Overlapping strings detected (start=%d, last-end=%d)" 71 71))
  cl--assertion-failed((> string-start last-string-end) "Overlapping strings detected (start=%d, last-end=%d)" (71 71) nil)
  python-nav-end-of-statement()
  python-nav-end-of-defun()
  python-info-current-defun()
  eval((python-info-current-defun) nil)
  eval-expression((python-info-current-defun) nil nil 127)
  funcall-interactively(eval-expression (python-info-current-defun) nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

**Comment by cpitclaudel** [comment] 2018-05-18 15:52
This is bug 30964 
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30964

**Comment by jorgenschaefer** [comment] 2018-05-18 16:59
Thank you for finding the upstream report! :-)

**Comment by galaunay** [comment] 2019-07-06 12:03
I am closing this, please re-open if still relevant.

**Closed by galaunay** 2019-07-06 12:03 UTC
Labels: Reported upstream, bug
