### ISSUE TITLE
elpy-folding--hide-leafs: Invalid function: hs-life-goes-on

### ISSUE THREAD

**Issue by SergiyKolesnikov** [jorgenschaefer/elpy#1824] opened 2020-07-23 13:37 UTC
# Summary

Invoking `elpy-folding--hide-leafs` results in an error message: 
```
elpy-folding--hide-leafs: Invalid function: hs-life-goes-on
```

# Steps to reproduce
Open a Python buffer and press `C-c @ C-f`

# My configuration
## OS
Debain testing (bullseye)

## Result of `(elpy-config)`
```
Elpy Configuration

Emacs.............: 26.3
Elpy..............: 1.34.0
Virtualenv........: my_venv (/home/<edited>)
Interactive Python: ipython 7.16.1 (/home/<edited>)
RPC virtualenv....: rpc-venv (/home/<edited>/.emacs.d/elpy/rpc-venv)
 Python...........: python3 3.8.4 (/home/<edited>/.emacs.d/elpy/rpc-venv/bin/python3)
 Jedi.............: 0.17.2
 Rope.............: 0.17.0
 Autopep8.........: 1.5.3
 Yapf.............: 0.30.0
 Black............: 19.10b0
Syntax checker....: flake8 (/home/<edited>/.emacs.d/elpy/rpc-venv/bin/flake8)

Warnings

Options

```

## Elpy configuration in my init.el
```
(elpy-enable)
(setq elpy-rpc-python-command "python3")
(setq elpy-test-runner 'elpy-test-pytest-runner)
(define-key elpy-refactor-map (kbd "f") 'elpy-black-fix-code)
(setq elpy-indent-offset 4)
(add-hook 'elpy-mode-hook
          (lambda ()
            (setq python-indent-offset elpy-indent-offset)
	    (setq highlight-indentation-offset elpy-indent-offset)))
(setq company-idle-delay 0) ;; no delay before idle complete
(global-set-key [C-tab] 'company-complete-common)
```

**Comment by xorb0ss** [comment] 2020-07-30 14:07
Can confirm this is also happening to me. Note also that `Invalid function: hs-life-goes-on` also appears any time I click anywhere - I assume because it thinks I’m trying to fold something.

**Comment by galaunay** [comment] 2020-08-05 13:17
Maybe a missing `require` somewhere.

Is it better after executing `(require 'hideshow)` ?

**Comment by spluque** [comment] 2020-08-11 17:36
@galaunay requiring hideshow before or after elpy is loaded makes no difference in my case, using the latest elpy from elpa (20200805.1736).  As far as I can tell, this issue seems to have been introduced in this latest version.

**Comment by neopku** [comment] 2020-08-18 09:40
I have the same error message when I use my mouse click on the text.

**Comment by neopku** [comment] 2020-08-27 16:18
I disabled the elpy code folding module, and the error message is gone.

**Comment by galaunay** [comment] 2020-09-26 18:18
`hs-life-goes-on` is part of Emacs since 19.0 so it should be around.
I tried with a clean Emacs -Q and just Elpy with the folding module activated, and it is not complaining so far.
Do you something related to hideshow.el in your configuration ?

**Comment by akovardakov** [comment] 2021-04-21 15:41
Get same error for all folding functions.
Also folding of code blocks like "for" or "if" does not work don't know if this is related or not.

**Comment by Yevgnen** [comment] 2021-12-03 06:24
@galaunay `hs-life-goes-on` is a macro instead of a function on my Emacs. Does it matter?

**Comment by mhlr** [comment] 2021-12-16 22:18
The fix is to add `(require 'hideshow)` to elpy.py. The issue is that `hs-life-goes-on` is a macro, so it's definition needs to be available when the code using it is being loaded/bytecompiled.

I have submitted a fix in #1952

**Comment by mhlr** [comment] 2022-02-03 00:55
What do I need to do to get #1952 reviewed & merged?

**Comment by gopar** [comment] 2022-02-03 01:08
> What do I need to do to get #1952 reviewed & merged?

Ask and ye shall receive lol

It's done. Please re-open if issue persists.

**Closed** 2022-02-03 01:08 UTC
