### ISSUE TITLE
elpy-format-code dosn't save the point location

### ISSUE THREAD

**Issue by gozes** [jorgenschaefer/elpy#1016] opened 2016-10-29 12:50 UTC
I have a before hook on my config so that after before a python file is save it will run elpy-format-code. However when elpy-format-code runs my cursor end up at the end of the buffer rather then stay where it is

**Comment by gopar** [comment] 2016-10-30 01:44
Hmmm, on my side that randomly happens. Sometimes it moves the cursor, sometimes it won't. I'm using `yapf`. One way to work around this is to add `save-excursion` inside the condition statements in `elpy-format-code`.

**Comment by landakram** [comment] 2016-11-02 21:50
I'm not 100% sure about this, but the behavior I'm seeing is that, if the buffer *does* reformat, then the cursor *doesn't* jump. If the buffer *doesn't* reformat, then the cursor *does* jump.

**Comment by jorgenschaefer** [comment] 2016-11-04 14:08
Could you post the output of `M-x elpy-config`? This was a bug in older versions of Elpy. Current versions should try to retain the line and column at least.

**Comment by aagaard** [comment] 2016-12-14 12:53
I have the same problem. Running Elpy 1.13.0.

**Comment by swarnendubiswas** [comment] 2017-03-15 23:33
Here is the output from `M-x elpy-config.`

```
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.5.2 (/workspace/software/Python-3.5.2/build/bin/python3)
Interactive Python: python3 (/workspace/software/Python-3.5.2/build/bin/python3)
Emacs.............: 25.1.1
Elpy..............: 1.14.1
Jedi..............: 0.10.0
Rope..............: 0.10.5
Importmagic.......: 0.1.7
Autopep8..........: 1.3.1
Yapf..............: 0.16.0
Syntax checker....: flake8 (/workspace/software/Python-3.5.2/build/bin/flake8)
```

**Comment by jorgenschaefer** [comment] 2017-03-16 11:38
Hm. `elpy--fix-code-with-formatter` will remember the line and column point was at before the code fix-up, and return there afterwards. I do not see why this should fail. Testing this localy, it also works for me.

I'm really sorry, but without a way to reproduce this, I'm a bit at a loss here. Can anyone of you debug this any further?

**Comment by jongukim** [comment] 2017-03-17 02:29
Same problem here when I run 'elpy-yapf-fix-code.
I'm running Elpy on my Windows 10 (64-bit).
Is there any way to see debug messages for you guys?

The followings are my Elpy Configuration.

Virtualenv........: None
RPC Python........: 3.5.3 (c:/Users/kju/AppData/Local/Programs/Python/Python35/python.exe)
Interactive Python: ipython (c:/Users/kju/AppData/Local/Programs/Python/Python35/Scripts/ipython.exe)
Emacs.............: 25.1.1
Elpy..............: 1.14.1
Jedi..............: 0.10.0
Rope..............: 0.9.4-1
Importmagic.......: 0.1.7
Autopep8..........: 1.3.1
Yapf..............: 0.16.0
Syntax checker....: flake8.exe (c:/Users/kju/AppData/Local/Programs/Python/Python35/Scripts/flake8.exe)

**Comment by jorgenschaefer** [comment] 2017-03-17 12:47
elpy--fix-code-with-formatter will always move to the last line/column …

Hm. Does `M-x elpy-yapf-fix-code` cause an error or something?

If you know elisp, could you add some debugging code to `elpy--fix-code-with-formatter` at the end around the `forward-line` call to see whether it actually tries to go to that line?

**Comment by sigma** [comment] 2017-06-11 19:20
@jorgenschaefer so I have the same problem, and `edebug`-ing through the code it appears that when `yapf` doesn't modify the content, `elpy-buffer--replace-region` doesn't do anything at all, therefore leaves `point` in place. After that, the `forward-line` call moves us somewhere else, which is basically line 2N, if we were initially at line N.

On the other hand, when there is a replacement, after the call to `elpy-buffer--replace-region` the point is at `(point-min)`, which makes the `forward-line` call correct. I'm not entirely sure I understand why we're there though, given the presence of `save-excursion` in `elpy-buffer--replace-region`.

Anyway, my current workaround is to modify `elpy--fix-code-with-formatter` as follows:
```lisp
...
(when (equal (point) (point-min))
  (forward-line (1- line))
  (forward-char col))
...
```

**Comment by jorgenschaefer** [comment] 2017-06-13 18:44
Hm. `elpy-buffer--replace-region` does not modify the buffer position if the replacement text is the same as before, so that  sounds like the right spot. Very nice debugging, thank you! Could you check if the change I pushed fixes things? (It's basically the same code as yours)

**Closed** 2017-06-13 18:43 UTC
Labels: bug

**Comment by sigma** [comment] 2017-06-13 20:48
@jorgenschaefer yep, that fixes things for me. thanks !
