### ISSUE TITLE
Undo after elpy-nav-move-region-or-line-right doesn't undo the indent on the first line

### ISSUE THREAD

**Issue by Sbte** [jorgenschaefer/elpy#589] opened 2015-06-10 17:55 UTC
If I indent a block of code

```
    aaa
    aaa
    aaa
```

using elpy-nav-move-region-or-line-right

```
        aaa
        aaa
        aaa
```

Using C-/

```
        aaa
    aaa
    aaa
```

I have tried to write a piece of code that does this, but I couldn't manage. Does anyone know why this is happening?

**Comment by jorgenschaefer** [comment] 2015-06-11 08:36
Thank you for the report!
This looks weird – the block moving commands of Elpy are somewhat broken at the moment, but this looks rather weird even with that in mind. I'll try and fix the region movement commands soon, hopefully this will be fixed then, too.

**Comment by jorgenschaefer** [comment] 2015-08-22 11:06
I can't reproduce this with the current development version (we changed the code that does the indent/dedent) – can you verify that this is fixed?

**Comment by Sbte** [comment] 2015-08-24 10:20
Seems to work much better. The only difference being that if you don't select the full first line it won't indent that line. I'd like it better if it could do that, but I guess I can live with this :P. Thanks!

**Comment by jorgenschaefer** [comment] 2015-08-25 13:37
Good point about the first line – maybe Elpy should "normalize" the region first.

**Closed** 2015-08-25 13:38 UTC
Labels: bug
