### ISSUE TITLE
completion from numbers to keywords?

### ISSUE THREAD

**Issue by abred** [jorgenschaefer/elpy#1123] opened 2017-04-20 13:38 UTC
hi,
elpy-company-backend tries to complete numbers to python keywords.
e.g.:
```
224 -> and [keyword]
       if  [keyword]
       ...
```
is this on purpose? I tried it with a clean setup, Emacs 25.1.1, only elpy installed.
(can provide more info if this turns out to be some bug)

**Comment by jorgenschaefer** [comment] 2017-04-21 09:19
No, this is not on purpose. Seems to be a bug in Jedi:

```Python
>>> s = jedi.Script("123", line=1, column=3)
>>> s.completions()
[<Completion: and>, <Completion: if>, <Completion: in>, <Completion: is>, <Completion: not>, <Completion: or>]
```

**Comment by jorgenschaefer** [comment] 2017-04-21 09:51
Duplicate of #1115, let's keep the discussion there.

**Closed by jorgenschaefer** 2017-04-21 09:51 UTC
Labels: bug
