### ISSUE TITLE
Package ‘s-1.10.0’ is unavailable

### ISSUE THREAD

**Issue by humblevladimirthegreat** [jorgenschaefer/elpy#1067] opened 2017-01-31 23:53 UTC
Hello, I'm very new to Emacs and can't seem to install Elpy on Ubuntu Server 14.04 and using Emacs 26.0.50.2

I followed your instructions here https://elpy.readthedocs.io/en/latest/introduction.html#installation
-I put the first 3 lines as shown (the file ~/.emacs was non-existent before then)
-I refresh the contents without issue (and it does say that it is contacting http://jorgenschaefer.github.io:80/)
-Attempting to install elpy yields "Package ‘s-1.10.0’ is unavailable"

I've tried searching both emacs and the web for a package called 's' but it's very difficult to find any results. Can you help point me in the right direction? Thanks!

**Comment by letuananh** [comment] 2017-02-01 02:57
I'm having the same problem right now.

**Comment by brandm** [comment] 2017-02-01 06:34
Duplicate of #1066

**Comment by jorgenschaefer** [comment] 2017-02-01 07:34
Thank you for the report! This should be fixed. Please comment on #1066 if this is still a problem. :-)

**Closed by jorgenschaefer** 2017-02-01 07:34 UTC
Labels: bug
