### ISSUE TITLE
Ubuntu 18.04 and ensurepip

### ISSUE THREAD

**Issue by akaszynski** [jorgenschaefer/elpy#1760] opened 2020-03-10 05:15 UTC
Thanks for the awesome emacs package!

Running `M-x elpy-config` failed to create the virtual environment, and it was due to a missing package `ensure pip`.  Ubuntu does not install `ensurepip` by default, and it took a bit of searching to discover that you need to have the `python3-venv` package installed with:
```bash
sudo apt install python3-venv
```

Please note this in the documentation somewhere for the latest version of `elpy`.

**Comment by galaunay** [comment] 2020-03-21 17:46
Just for my personal record,  [here](https://bugs.launchpad.net/ubuntu/+source/python3.4/+bug/1290847) is the related bug report on ubuntu.

**Comment by galaunay** [comment] 2020-03-21 17:49
@sten0 have you run into this issue on debian, or is it a ubuntu-only issue ?

**Comment by sten0** [comment] 2020-03-22 00:47
Sorry, no idea, because I don't use MELPA, and because I spend my time
making sure the elpa-elpy_$version.deb works out of the box, and that your
upstream defaults (the new virtualenv method of providing Elpy deps) can be
restored per README.Debian.

Iirc Ubuntu 20.04 will have the latest tagged release (as of now) of
elpa-elpy, which I indirectly support as Debian upstream to Ubuntu.  That
said, Ubuntu support ultimately falls to their small universe/multiverse
team and/or any breakage caused by their Python team.

If this is a bug in the deb package of Elpy I'd appreciate steps to
reproduce, because a reproducible bug is actionable, and with this info I
have a duty to fix such issues.

Cheers,
Nick

**Comment by galaunay** [comment] 2020-03-23 11:08
Thanks Nick, 

If it is just a ubuntu problem, I'll just add a check for `ensurepip` and warn the user if necessary.

@akaszynski I didn't add this to the documentation, but Elpy will now warn the user if `ensurepip` is missing and indicates that the `venv` package should be installed.

I am closing this, please re-open if necessary.

**Closed by galaunay** 2020-03-23 11:08 UTC

**Comment by 0trenixjetix** [comment] 2021-07-08 10:08
I'm having this error after running elpy-config
Also elpy doesn't autoactivate the virtual environment

```Running 'python3 -m venv /home/jorge/.emacs.d/elpy/rpc-venv':

The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/jorge/.emacs.d/elpy/rpc-venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']



Elpy failed to install its dedicated virtualenv due to the above
error. If the error details does not help you fixing it, You can
report this problem on Elpy repository on github.
In the meantime, setting the `elpy-rpc-virtualenv-path' option to
either `system' or `current' should temporarily fix the issue.```
