### ISSUE TITLE
Need package cl-generic-1.0, but only 0.3 is available

### ISSUE THREAD

**Issue by amirteymuri** [jorgenschaefer/elpy#1173] opened 2017-09-08 11:02 UTC
I get the above error when trying to `package-install` elpy. I have searched internet, it seems the latest version of cl-generic is 0.3 from 2016. How should i solve this dependency problem?

**Comment by peterwvj** [comment] 2017-09-08 15:57
I use EVM and Travis to check that my configuration loads everytime I change it. Recent changes in Elpy suddenly causes an error when I try to load my configuration in Emacs 24.5 and bleeding edge snapshots. However, Elpy still loads successfully in Emacs 25.1.

I believe the following is the relevant part of the error:

```bash
Debugger entered--Lisp error: (error "Need package `cl-generic-1.0', but only 0.3 is available")
  signal(error ("Need package `cl-generic-1.0', but only 0.3 is available"))
  error("Need package `%s-%s', but only %s is available" cl-generic "1.0" "0.3")
  package-compute-transaction(([cl-struct-package-desc elpy (20170903 143) "Emacs Python Development Environment" ((company (0 9 2)) (find-file-in-project (3 3)) (highlight-indentation (0 5 0)) (pyvenv (1 3)) (yasnippet (0 8 0)) (s (1 11 0)) (cl-generic (1 0))) tar "melpa" nil ((:commit . "d1cfe9c87031a9fd4c9754afdc4c4d0b3b3128a6")) nil]) ((company (0 9 2)) (find-file-in-project (3 3)) (highlight-indentation (0 5 0)) (pyvenv (1 3)) (yasnippet (0 8 0)) (s (1 11 0)) (cl-generic (1 0))) ([cl-struct-package-desc elpy (20170903 143) "Emacs Python Development Environment" ((company (0 9 2)) (find-file-in-project (3 3)) (highlight-indentation (0 5 0)) (pyvenv (1 3)) (yasnippet (0 8 0)) (s (1 11 0)) (cl-generic (1 0))) tar "melpa" nil ((:commit . "d1cfe9c87031a9fd4c9754afdc4c4d0b3b3128a6")) nil]))
  package-compute-transaction(nil ((elpy)))
  package-install(elpy)
....
```

**Comment by robotenique** [comment] 2017-09-09 04:16
I have the same problem, emacs 24.5.1

**Comment by Ra1nyHouse** [comment] 2017-09-11 07:58
I have the same problem. How can we do?

**Comment by Ra1nyHouse** [comment] 2017-09-11 08:24
Oh, I solve this problem by setting
```
(add-to-list 'package-archives
             '("elpy" . "http://jorgenschaefer.github.io/packages/"))
```
Do not use elpa or gnu's package-archives.

**Comment by svetlyak40wt** [comment] 2017-09-17 17:31
Interesting, I've excluded everything except http://jorgenschaefer.github.io/packages/, like that:

```lisp
(setq package-archives '(("elpy" . "https://jorgenschaefer.github.io/packages/")))
```

But now I see only these packages avalable and no elpy:

```
  buttercup          1.0           available  Behavior-Driven Emacs Lisp Testing
  fuzzy              0.1           available  Fuzzy Matching
  idomenu            0.1           available  imenu tag selection with ido
  iedit              0.97          available  Edit multiple regions in the same way simultaneously.
```

Why?

Emacs's version is `GNU Emacs 24.5.1 (x86_64-pc-linux-gnu) of 2016-04-17`.

**Comment by Ra1nyHouse** [comment] 2017-09-18 02:54
Do not use the function `setq`. It would overwrite the default archives' URL. Maybe `add-to-list` is a better choice. 
Or you could use my config like 
```
(setq package-archives '(
			   ("gnu"   . "http://elpa.emacs-china.org/gnu/")
			   ("melpa" . "http://elpa.emacs-china.org/melpa/")
			   ("elpy" . "http://jorgenschaefer.github.io/packages/")
			   )
	)
 ```
Spicially, I use the `setq` function because I want to overwrite the default settings. I choose other mirrors so that I can download archives fast.

**Comment by alfalfasprossen** [comment] 2017-09-20 20:41
`cl-generic-1.0` is built-in since emacs 25.0 (or so). The `cl-generic-0.3` may only be a backport for older emacs versions. 

There seems to be a problem with package.el though, which will attempt to download the required version package, even if it is already built-in, and since `1.0` doesn't exist in the package repositories, will fail. At least that seems to have been the case in emacs < 25.1. But must have been fixed in newer versions, as the current 25.3 release works fine for me.

So, requiring `cl-generic-1.0` probably won't work with emacs versions prior to 25, unless it is provided in a package repository.

**Comment by asipser** [comment] 2017-09-21 01:12
Also running into this issue! Running emacs 24.5, and want to use elpy. Has anybody found any workarounds?

**Comment by jorgenschaefer** [comment] 2017-09-22 10:22
Thank you all for the reports and updates, and sorry that it took a while for me to respond. I just pushed a new version that gets rid of the dependency altogether. Tests are green, so I guess this still works on all Emacsen. Let me know if there are further problems.

**Comment by TheShadow29** [comment] 2017-09-22 12:03
@jorgenschaefer Unfortunately I am still running into the error. Using emacs 24.5. 
I put this into .emacs file
```
(require 'package)
(add-to-list 'package-archives
			 '("elpy" . "http://jorgenschaefer.github.io/packages/"))
```
And then run `M-x package-refresh-contents`. Up to this point there is no problem.
When I do `M-x package-install elpy` I run into the same error which is
Need package `cl-generic-1.0', but only 0.3 is available.

**Comment by jorgenschaefer** [comment] 2017-09-22 13:30
Does it try to install Elpy 1.16.1?

**Comment by TheShadow29** [comment] 2017-09-25 05:31
@jorgenschaefer how do I check which version is it trying to install?

**Comment by peterwvj** [comment] 2017-09-27 20:10
I can confirm that Elpy now works in Emacs 24.5 with my configuration.

**Comment by jorgenschaefer** [comment] 2017-09-29 12:22
Awesome – thank you!

**Closed by jorgenschaefer** 2017-09-29 12:22 UTC
