### ISSUE TITLE
Read Python Code 

### ISSUE THREAD

**Issue by xuehao** [jorgenschaefer/elpy#489] opened 2015-02-10 15:00 UTC
Dear Jorgen,
I find reading Python code in Emacs is very annoying. Is there any solution to solve it, like 'Outline' in Eclipse or 'Hierarchy Callers of code' in PyCharm?

**Comment by whirm** [comment] 2015-02-10 15:05
@xuehao have you tried semantic? I use ```helm-semantic``` all the time.

It looks like this:

![2015-02-10-160311_3120x1920_scrot](https://cloud.githubusercontent.com/assets/529494/6129402/9500149e-b13e-11e4-9388-a05b153e2051.png)

**Comment by jorgenschaefer** [comment] 2015-02-10 16:08
Dear xuehao,
Thank you for the question. I am afraid the whole folding issue is a bit of a problem in Emacs in general. You have a number of different options, none of which I can recommend wholeheartedly as the best solution, but maybe one of them works for you.

- Emacs' python-mode, which Elpy uses, comes with support for outline-mode, which also ships with Emacs, so you can use `outline-minor-mode` for folding; see [the emacs manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Outline-Mode.html) for more details
- Likewise, the mode supports the hide-show minor mode that comes with emacs, `hs-minor-mode`, also for folding; see again [the manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Hideshow.html) for more information.
- The mode also integrates with imenu. This gives you `M-x imenu` as well as an outline in `M-x speedbar` (if you dislike the separate frame for speedbar, there is the external `sr-speedbar` package which might help).
- Finally, Elpy comes with an outlining feature, by default bound to `C-c C-o`, which gives you an overview of the structure of the current file.

There are other solutions, for example the helm-semantic package @whirm describes above.

I hope one of these will make reading Python code in Emacs less annoying.

**Comment by xuehao** [comment] 2015-02-11 13:15
Thank you, Jorgen! I like the style of ELPY `C-c C-o`. It's what I want. Also thank you @whirm , I'll try semantic.

**Comment by bersace** [comment] 2015-02-13 13:47
Nice !

Closing ?

**Comment by jorgenschaefer** [comment] 2015-04-12 15:27
Yeah. I assume the problem is solved. Please do not hesitate to create a new issue if you have any further problems, and enjoy Elpy. :-)

**Closed by jorgenschaefer** 2015-04-12 15:27 UTC
Labels: question
