### ISSUE TITLE
Failed to setup thread-interrupt handler.

### ISSUE THREAD

**Issue by whirm** [jorgenschaefer/elpy#458] opened 2015-01-28 19:26 UTC
current ```master``` keeps failing with the following error:

```
Error initializing Elpy

There was an error when trying to start the backend. Elpy can not work until this problem is solved. The following lines
were received from Python, and might help identifying the problem.

Failed to setup thread-interrupt handler. This is usually not critical
```

How to reproduce:

 * Open any python file

 * The mentioned error pops up.

if I type something (I just pressed ```s```) and wait a moment I get this:

```
Error initializing Elpy

There was an error when trying to start the backend. Elpy can not work until this problem is solved. The following lines
were received from Python, and might help identifying the problem.

Failed to setup thread-interrupt handler. This is usually not critical
{"result": [{"annotation": "class", "meta": "set (builtin, class)", "name": "set", "suffix": "et"}, {"annotation": "function", "meta": "setattr (builtin, function)", "name": "setattr", "suffix": "etattr"}, {"annotation": "module", "meta": "sha (imported, module)", "name": "sha", "suffix": "ha"}, {"annotation": "class", "meta": "slice (builtin, class)", "name": "slice", "suffix": "lice"}, {"annotation": "function", "meta": "sorted (builtin, function)", "name": "sorted", "suffix": "orted"}, {"annotation": "class", "meta": "staticmethod (builtin, class)", "name": "staticmethod", "suffix": "taticmethod"}, {"annotation": "class", "meta": "str (builtin, class)", "name": "str", "suffix": "tr"}, {"annotation": "function", "meta": "sum (builtin, function)", "name": "sum", "suffix": "um"}, {"annotation": "function", "meta": "super (builtin, function)", "name": "super", "suffix": "uper"}], "id": 6}
```

if I go back to ```release``` everything works fine.

Thanks!

**Comment by birkenfeld** [comment] 2015-01-29 07:05
This is likely caused by the import of a C extension by `importmagic` (importmagic is the newly used library to provide automatic importing, so it builds an index of available symbols by iterating over all modules, parsing .py files and importing .c files.)

I'm not sure how to handle this; temporarily changing `sys.stdout` wouldn't help for those anyway. We could call importmagic in a subprocess, but that would be much easier with a working index caching implementation in importmagic.

**Comment by whirm** [comment] 2015-01-29 11:06
Ok, Found it: it's python-async's __init__.py:

```python
def _init_signals():
	"""Assure we shutdown our threads correctly when being interrupted"""
	import signal
	import thread
	import sys
	
	prev_handler = signal.getsignal(signal.SIGINT)
	def thread_interrupt_handler(signum, frame):
		thread.do_terminate_threads()
		if callable(prev_handler):
			prev_handler(signum, frame)
			raise KeyboardInterrupt()
		# END call previous handler
	# END signal handler
	try:
		signal.signal(signal.SIGINT, thread_interrupt_handler)
	except ValueError:
		# happens if we don't try it from the main thread
		print >> sys.stderr, "Failed to setup thread-interrupt handler. This is usually not critical"
	# END exception handling

```

Why don't you use file descriptor 3 for the RPC pipe?

**Comment by jorgenschaefer** [comment] 2015-01-29 11:44
@whirm, primarily because Emacs makes it tricky to do so. :-)
("Tricky" meaning "I do not know how we could do that". Emacs does not even make it possible to distinguish stdout from stderr, and I do not see any way to read another file descriptor, either.)

I consider it a bug for a library to write to stdout/stderr, but this has happened a few times now. I guess it's time for Elpy to deal with this somehow. I have created #461 to track this new feature for Elpy 1.8.

A hack to solve the specific problem in this issue would be to run importmagic in the main thread and the main Elpy interaction in the other thread. Not sure I like it, but I do not see a good fix that would make it for Elpy 1.7.

**Comment by jorgenschaefer** [comment] 2015-02-01 15:20
The fix points stderr to /dev/null, as Elpy does not use stderr for communication. This should solve this particular problem until #461 can do a proper job.

The async library I installed locally did not have the code there in it, so I did not actually _test_ it … @whirm, did I get it right? :o)

**Comment by whirm** [comment] 2015-02-01 21:41
I've upgraded to 4399c86bcdf02d36bf105b8bf3f4894a9eaa593f and reinstalled python-async.

Now I get a different one :( (I'm trying to figure out where it comes from)
```
Error initializing Elpy

There was an error when trying to start the backend. Elpy can not work until this problem is solved. The following lines
were received from Python, and might help identifying the problem.

--------------------------------------------------------------------------
[[11480,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: carbon

Another transport will be used instead, although this may result in
lower performance.
--------------------------------------------------------------------------
{"result": [{"annotation": "instance", "meta": "self (local, instance)", "name": "self", "suffix": "elf"}, {"annotation": "class", "meta": "set (builtin, class)", "name": "set", "suffix": "et"}, {"annotation": "function", "meta": "setattr (builtin, function)", "name": "setattr", "suffix": "etattr"}, {"annotation": "module", "meta": "sha (imported, module)", "name": "sha", "suffix": "ha"}, {"annotation": "class", "meta": "slice (builtin, class)", "name": "slice", "suffix": "lice"}, {"annotation": "function", "meta": "sorted (builtin, function)", "name": "sorted", "suffix": "orted"}, {"annotation": "class", "meta": "staticmethod (builtin, class)", "name": "staticmethod", "suffix": "taticmethod"}, {"annotation": "class", "meta": "str (builtin, class)", "name": "str", "suffix": "tr"}, {"annotation": "function", "meta": "sum (builtin, function)", "name": "sum", "suffix": "um"}, {"annotation": "function", "meta": "super (builtin, function)", "name": "super", "suffix": "uper"}], "id": 6}
```

I'm trying to figure out where this is coming from as a grep trough /usr/ only shows a couple of text files:

```bash
└──> sudo rgrep -i "Another transport will be used" 
share/doc/openmpi-bin/README.Debian:  Another transport will be used instead, although this may result in 
share/openmpi/help-mpi-btl-base.txt:Another transport will be used instead, although this may result in
```

And I don't even have python-mpi or python-scipy installed...

**Comment by birkenfeld** [comment] 2015-02-01 22:04
For grepping, make sure your grep doesn't treat binary files as "no match".
Otherwise, you can add some debug output to `importmagic/index.py` in the method `index_builtin()`.

**Comment by whirm** [comment] 2015-02-01 22:12
@birkenfeld  Turns out /usr/share/openmpi/help-mpi-btl-base.txt is a template for the error I got, I'll add some debug info tomorrow and see.

**Comment by jorgenschaefer** [comment] 2015-02-02 09:27
Hm. This is weird – the same problem should happen with the current release branch if e.g. Jedi or Rope try to import that module in the main thread. Which would happen if you try to auto-complete openmpi modules of some sort.

Is this the case?

**Comment by whirm** [comment] 2015-02-02 11:32
with ```release```:
```

Virtualenv........: None
RPC Python........: 2.7.9 (/usr/bin/python)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 24.4.1
Elpy..............: 1.6.0
Jedi..............: 0.8.1-final0
Rope..............: 0.10.2
Syntax checker....: pyflakes (/usr/bin/pyflakes)
```
Everything looks fine.
with ```master```:
```
Virtualenv........: None
RPC Python........: 2.7.9 (/usr/bin/python)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 24.4.1
Elpy..............: 1.6.1
Jedi..............: 0.8.1-final0
Rope..............: 0.10.2
Importmagic.......: 0.1.2
Syntax checker....: pyflakes (/usr/bin/pyflakes)
```
....it works too! now I can't reproduce it! :/  

I'm suspecting some .elc hung around when I updated yesterday? (today I made sure nothing was left)

Close the issue, I'll reopen it if I manage to reproduce it.

**Comment by whirm** [comment] 2015-02-13 18:33
Ok, I'm able to reproduce it consistently now:
The culprit is ```boost.mpi.x86_64-linux-gnu```

/usr/lib/python2.7/dist-packages/boost/__init__.py which contains:
```python
import sys
if sys.platform == 'linux2':
    import DLFCN as dl
    flags = sys.getdlopenflags()
    sys.setdlopenflags(dl.RTLD_NOW|dl.RTLD_GLOBAL)
    import mpi
    sys.setdlopenflags(flags)
else:
    import mpi
```
loads ```mpi.x86_64-linux-gnu.so``` which prints this warning message. 

@jorgenschaefer I guess I never triggered this with an older release because I've never used this module.

**Comment by jorgenschaefer** [comment] 2015-02-14 10:01
Heh, nice find. I'd like to say "modules should not print to stdout/stderr!" and be done with it, but that's not helpful. Really, as long as Elpy has not full control over the communication channel, it should not be confused by out of band text.

**Comment by jorgenschaefer** [comment] 2015-04-24 08:43
Oh, I had totally missed this issue because I forgot to move it to an open milestone.

Does this still happen?

**Comment by jorgenschaefer** [comment] 2015-08-22 10:47
Lacking updates on this, I am closing this issue. Please do not hesitate to open a new issue if there are further problems!

**Closed by jorgenschaefer** 2015-08-22 10:47 UTC
Labels: bug
