### ISSUE TITLE
extra '=' in the completion candidate

### ISSUE THREAD

**Issue by enzochiau** [jorgenschaefer/elpy#613] opened 2015-07-15 01:16 UTC
When I try to type code as below:

    def go2str(foo):
        return str(fo

The completion candidate is `foo=`, not "foo" as what I expected.

**Comment by jorgenschaefer** [comment] 2015-07-15 08:41
Hello, and thank you for the report.

I have seen this before, but I was never able to reproduce it reliably. E.g. when I enter the code in your example in a new file, the completion works as expected.

I hope we can find out when this is happening so it can be fixed in Jedi upstream. :-/

**Comment by emacsway** [comment] 2015-09-10 20:44
Hi, @jorgenschaefer. I've same problem http://joxi.ru/KAgknX7tM7ZNAl
My config: https://bitbucket.org/emacsway/.emacs.d/src

**Comment by jorgenschaefer** [comment] 2015-09-12 11:42
Thank you for the update. This seems to be a bug in Jedi, where it thinks that some variables are named arguments to the function as opposed to a local variable, so it adds the equal operator.

Sadly, when I try to narrow down the problem, it generally goes away quickly, so I have no good reproduction case to file a report with Jedi.

**Closed** 2015-10-29 16:57 UTC
Labels: bug
