### ISSUE TITLE
Slow auto-completion for large DataFrame containing strings

### ISSUE THREAD

**Issue by flcong** [jorgenschaefer/elpy#1853] opened 2020-11-18 19:08 UTC
This is related to #1095 and #1657. I am not sure why, but it seems the autocompletion is especially slow for large DataFrame with strings (object) in it.

For example, consider the following two DataFrames:

```python
import numpy as np
import pandas as pd
df1 = pd.DataFrame(np.random.rand(400000,60))
df2 = pd.DataFrame([["asdfasdf"]*60]*400000)
```

By typing `df1.<TAB>` in the interactive python, the autocompletion is quick, but it takes a very long time for `df2.<TAB>` to complete. I tried by launching Emacs clean `emacs -q`.

I am not an expert on this, but it seems to me that the procedure for auto-completion for DataFrames containing only numbers or strings should be the same, so I'm not sure why it takes so long for the latter but not the former. Correct me if I am wrong.

**Comment by gopar** [comment] 2020-11-18 21:08
This is interesting. `[Jedi](https://jedi.readthedocs.io/en/latest/)` is what `elpy` uses to provide completion (elpy itself doesn't do any autocompletion). I would be surprised if jedi was evaluating the expression to try to get completion suggestions. 

Best bet is to bring it up to their Issue tracker (if you can reproduce with just the python jedi package by itself) otherwise, this is a problem that elpy is introducing somewhere

**Comment by flcong** [comment] 2020-11-18 22:22
> This is interesting. `[Jedi](https://jedi.readthedocs.io/en/latest/)` is what `elpy` uses to provide completion (elpy itself doesn't do any autocompletion). I would be surprised if jedi was evaluating the expression to try to get completion suggestions.
> 
> Best bet is to bring it up to their Issue tracker (if you can reproduce with just the python jedi package by itself) otherwise, this is a problem that elpy is introducing somewhere

Sorry, I just realize that I was referring to the auto-completion in the interactive python within Emacs. Then, I find that the same issue exists in any interactive python sessions, e.g. run `python` in the command line. The auto-completion when editing python code files in Emacs works fine. I should probably close this issue.

**Comment by gopar** [comment] 2020-11-19 01:24
What is bound to `<TAB>` in interactive shell? Do you have any settings related to interactive shell? From what I can recall elpy doesn't provide completion in the shell (maybe that has changed, been inactive for a long time)

**Comment by flcong** [comment] 2020-11-19 03:29
> What is bound to `<TAB>` in interactive shell? Do you have any settings related to interactive shell? From what I can recall elpy doesn't provide completion in the shell (maybe that has changed, been inactive for a long time)

It's `python-shell-completion-complete-or-indent` with source code at `c:/Emacs/x86_64/share/emacs/27.1/lisp/progmodes/python.el`. I simply run `M-x run-python` to open the interactive shell and am using doom emacs.

**Comment by flcong** [comment] 2020-11-19 03:41
Actually, it only happens if I type `df2.<TAB>`. If I give an initial letter, it is okay, e.g. `df2.a<TAB>`.

**Comment by gopar** [comment] 2020-11-19 20:58
Hmm this sounds like it might be a problem with the internals of emacs (or at least a function that `python-shell-complete-or-indent` is deferring to). Do you get completion with interactive shell via the terminal? If so can you reproduce there? 
If you can reproduce in stand alone interactive shell, then the problem is with whatever python shell is doing to provide results. Otherwise there has to be something in emacs that is introducing that issue.

**Comment by flcong** [comment] 2020-11-20 01:19
I also report to pandas (https://github.com/pandas-dev/pandas/issues/37947). It seems to be the issue of `jedi`. The problem also exists in interactive via the terminal as well and only `df2.T<TAB>` or `df2.<TAB>` get stuck (`df2.[any letter except T]<TAB>` is fine).

**Comment by gopar** [comment] 2020-11-20 02:46
Aweome, then this is not an issue relating to elpy.

Closing \o/

**Closed by gopar** 2020-11-20 02:46 UTC
