### ISSUE TITLE
elpy fails to recognize celery keyword

### ISSUE THREAD

**Issue by kirang89** [jorgenschaefer/elpy#640] opened 2015-08-24 00:43 UTC
I'm not sure why, but elpy(or rather jedi) keeps crashing when I try to write a celery task.

Configuration:
```
Virtualenv........: env (/Users/kiran/Workspace/myapp/env)
RPC Python........: 2.7.6 (/Users/kiran/Workspace/myapp/env/bin/python)
Interactive Python: python (/Users/kiran/Workspace/myapp/env/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.8.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.2 available)
Importmagic.......: Not found (0.1.3 available)
Syntax checker....: flake8 (/usr/local/bin/flake8)
```

Traceback:
```
Traceback (most recent call last):
  File "/Users/kiran/.emacs.d/elpa/elpy-20150502.740/elpy/jedibackend.py", line 303, in run_with_debug
    return getattr(script, name)()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/api/__init__.py", line 515, in call_signatures
    stmt = self._get_under_cursor_stmt(call_txt, start_pos)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/api/__init__.py", line 309, in _get_under_cursor_stmt
    user_stmt = self._parser.user_stmt()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/parser/user_context.py", line 293, in user_stmt
    module = self.module()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/parser/user_context.py", line 339, in module
    return self._parser().module
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/parser/user_context.py", line 283, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/parser/fast.py", line 109, in __call__
    p.update(source)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/parser/fast.py", line 383, in _parse
    line_offset, nodes)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/parser/fast.py", line 435, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 106, in parse
    if self.addtoken(type, value, prefix, start_pos):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 170, in addtoken
    value, start_pos, prefix, self.addtoken)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/parser/__init__.py", line 269, in error_recovery
    self._stack_removal(grammar, stack, index + 1, value, start_pos)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/parser/__init__.py", line 304, in _stack_removal
    clear_names(children=node[1])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/parser/__init__.py", line 298, in clear_names
    self._scope_names_stack[-1][c.value].remove(c)

KeyError: u'celery'
```

**Comment by ChillarAnand** [comment] 2015-08-25 12:39
Thanks for the report. Looks like a jedi bug. If possible, can you post a simple reproduction case?

**Comment by jorgenschaefer** [comment] 2015-08-25 13:40
Thank you for the report! This was reported before as #593 and will be fixed (sadly, only by ignoring the error) in the next release of Elpy.

**Closed by jorgenschaefer** 2015-08-25 13:40 UTC

**Comment by kirang89** [comment] 2015-08-25 17:29
Thanks for the update!

@ChillarAnand: You can reproduce this by trying to define a celery task
