### ISSUE TITLE
Running any command prepends a long string to every output

### ISSUE THREAD

**Issue by rsuhada** [jorgenschaefer/elpy#1586] opened 2019-04-22 10:46 UTC
# Summary
Running any command prepends a long string to every command output:

>  import sys, codecs, os, ast, readline;__pyfile = codecs.open('''/tmp/pyw50Zmi''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/tmp/pyw50Zmi''');__block = ast.parse(__code, '''/home/XXXXXXX.py''', mode='exec'); __block.body = (__block.body if not isinstance(__block.body[0], ast.If) else __block.body if not isinstance(__block.body[0].test, ast.Name) else __block.body if not __block.body[0].test.id == 'True' else __block.body[0].body) if sys.version_info[0] < 3 else (__block.body if not isinstance(__block.body[0], ast.If) else __block.body if not isinstance(__block.body[0].test, ast.NameConstant) else __block.body if not __block.body[0].test.value is True else __block.body[0].body);__last = __block.body[-1];__isexpr = isinstance(__last,ast.Expr);_ = __block.body.pop() if __isexpr else None;exec(compile(__block, '''/home/rxsXXXX.py''', mode='exec'));eval(compile(ast.Expression(__last.value), '''/home/XXXXXXXX.py''', mode='eval')) if __isexpr else None

(I replaced the paths/filenames with Xs)

# Steps to reproduce
Running any command with e.g. `elpy-shell-send-statement-and-step`

# My configuration
## OS
Ubuntu 18.04

## Result of `(elpy-config)`
```
Virtualenv........: None
RPC Python........: 3.7.3 (/home/XXX/anaconda3/bin/python)
Interactive Python: python (/home/XXX/anaconda3/bin/python)
Emacs.............: 26.2
Elpy..............: 1.28.0
Jedi..............: 0.13.3
Rope..............: 0.12.0
Autopep8..........: Not found (1.4.4 available)
Yapf..............: Not found (0.27.0 available)
Black.............: Not found (19.3b0 available)
Syntax checker....: Not found (flake8)
```

## Elpy configuration in my init.el
```
(use-package elpy
  ;; usel m-x elpy-config to check/debug pathsA
  :ensure t
  :defer t
  :init
  ;; to get rid of the annoying message
  (add-to-list 'warning-suppress-types '(undo discard-info))
  :config
  (elpy-enable)
  (flymake-mode-off)
  (setq elpy-rpc-backend "jedi")
  ;; (setq elpy-rpc-backend "python3")

  (defun elpy-goto-definition-or-rgrep ()
    "Go to the definition of the symbol at point, if found. Otherwise, run `elpy-rgrep-symbol'."
    (interactive)
    (ring-insert find-tag-marker-ring (point-marker))
    (condition-case nil (elpy-goto-definition)
      (error (elpy-rgrep-symbol
              (concat "\\(def\\|class\\)\s" (thing-at-point 'symbol) "(")))))
  (define-key elpy-mode-map (kbd "M-.") 'elpy-goto-definition-or-rgrep)

  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;;
  ;; ESS-mode like behaviour
  ;;
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

  (defun elpy-shell-send-current-statement-and-stay-put ()
    "Send current statement to Python shell."
    (interactive)
    (let ((beg (python-nav-beginning-of-statement))
          (end (python-nav-end-of-statement)))
      (elpy-shell-get-or-create-process)
      (python-shell-send-string (buffer-substring beg end)))
    (elpy-shell-display-buffer)
    )
  (define-key elpy-mode-map (kbd "<S-return>") 'elpy-shell-send-current-statement-and-stay-put)

  (defun python-para-send-and-step ()
    "Sends the current paragraph to the python REPL and goes to the next one"
    (interactive)
    (mark-paragraph)
    (elpy-shell-get-or-create-process)
    (python-shell-send-region (region-beginning) (region-end))
    (elpy-shell-display-buffer)
    (deactivate-mark)
    (forward-paragraph)
    (python-nav-forward-statement)
    )

  (defun send-region-or-para-and-step ()
    (interactive)
    (if (use-region-p)
        (progn
          (elpy-shell-get-or-create-process)
          (python-shell-send-region (region-beginning) (region-end))
          (elpy-shell-display-buffer)
          (goto-char (region-end))
          (deactivate-mark)
          (python-nav-forward-statement)
          )
      (python-para-send-and-step)))

  (define-key elpy-mode-map (kbd "C-c C-c") 'send-region-or-para-and-step)
  (define-key elpy-mode-map (kbd "C-c C-n") 'sk/python-str)
  (define-key elpy-mode-map (kbd "C-c C-v") 'sk/python-help)
  (define-key elpy-mode-map (kbd "C-c C-b") 'elpy-shell-send-region-or-buffer)
  (define-key elpy-mode-map (kbd "M-]") 'ess-separator-major)
  (define-key elpy-mode-map (kbd "M-}") 'ess-separator-minor)
  )
```

**Comment by gopar** [comment] 2019-04-23 07:35
Can verify this.

**Comment by galaunay** [comment] 2019-04-26 10:31
Yes, I merged a bad commit a while ago (my bad).
It should be fixed in elpy 1.29.1, could you try updating elpy ?

**Comment by galaunay** [comment] 2019-09-05 15:36
I hope it works.
Please re-open if not.

**Closed by galaunay** 2019-09-05 15:36 UTC

**Comment by waqarsaleem** [comment] 2019-10-27 07:19
I have the same problem which I believe is also the cause for this issue: https://github.com/jorgenschaefer/elpy/issues/1550

# Environment
- elpy 1.31.0
- GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-09-02
- macOS Catalina 10.15
 
# .emacs
```
;; ;; Use python3 for python interpreter
;; (setq python-shell-interpreter "python3"
;;       python-shell-interpreter-args "-i")
;; Remove annoying readline warning when python loads
;; https://emacs.stackexchange.com/a/35969/11143
(setq python-shell-completion-native-disabled-interpreters '("python"))
;; https://emacs.stackexchange.com/a/30970/11143
(with-eval-after-load 'python
  (defun python-shell-completion-native-try ()
    "Return non-nil if can trigger native completion."
    (let ((python-shell-completion-native-enable t)
          (python-shell-completion-native-output-timeout
           python-shell-completion-native-try-output-timeout))
      (python-shell-completion-native-get-completions
       (get-buffer-process (current-buffer))
       nil "_"))))

;; Enable ELPY, python IDE
(elpy-enable)
(setq elpy-rpc-backend "jedi")  
;; Use IPython for REPL
(setq python-shell-interpreter "jupyter"
      python-shell-interpreter-args "console --simple-prompt"
      python-shell-prompt-detect-failure-warning nil)
(add-to-list 'python-shell-completion-native-disabled-interpreters
              "jupyter")
;; Enable Flycheck
(when (require 'flycheck nil t)
  (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
  (add-hook 'elpy-mode-hook 'flycheck-mode))
;; Enable autopep8
(require 'py-autopep8)
(add-hook 'elpy-mode-hook 'py-autopep8-enable-on-save)
```
# Elpy Configuration
```
Virtualenv........: None
RPC Python........: 2.7.16 (/usr/bin/python)
Interactive Python: python3 (/Library/Frameworks/Python.framework/Versions/3.8/bin/python3)
Emacs.............: 26.3
Elpy..............: 1.31.0
Jedi..............: 0.15.1
Rope..............: Not found (0.14.0 available)
Autopep8..........: 1.4.4
Yapf..............: Not found (0.28.0 available)
Black.............: Not found (19.3b0 available)
Syntax checker....: flake8 (/Library/Frameworks/Python.framework/Versions/3.8/bin/flake8)
```

**Comment by galaunay** [comment] 2019-10-29 16:11
Is it better with `elpy-shell-echo-output` set to `nil` ?

**Comment by waqarsaleem** [comment] 2019-10-30 09:12
Thanks, that helps. I can now use python3 and IPython for REPL. The Jupyter REPLT receives the buffer contents and does not show any extraneous text but does not seem to evaluate the recipe code and hangs. It then has to be killed with `C-c C-k`.

**Comment by galaunay** [comment] 2019-11-10 02:28
I merged a PR today (#1712) that may help.
Could you check if it is still happening with the latest version ?

**Comment by waqarsaleem** [comment] 2019-11-10 11:57
I already have `elpy-shell-echo-output` set to `nil` and things were working fine. I updated espy through the package manager after reading your message. Things still seem to be fine. How do you want me to test?

**Comment by galaunay** [comment] 2019-11-11 10:31
I thought you said it was still not working with the jupyter repl ?
> The Jupyter REPL receives the buffer contents and does not show any extraneous text but does not seem to evaluate the recipe code and hangs.

**Comment by waqarsaleem** [comment] 2019-11-15 11:48
Thanks for reminding. I had forgotten about this. I upgraded to 1.32.0 and the problem persists.
