### ISSUE TITLE
Alternative profiling visualisers

### ISSUE THREAD

**Issue by sten0** [jorgenschaefer/elpy#1631] opened 2019-08-11 22:26 UTC
Hi,

I just noticed `elpy-profile-buffer-or-region` in docs/ide.rst.  How does snakeviz compare to alternatives such as ProfileViewer/RunSnakeRun, vprof, CProfileV, or pythontracer?

It seems like it would be nice to populate the defcustom menu (https://github.com/jorgenschaefer/elpy/blob/7acdd14eaec4b123ae1c16ead59c91adcf7f9775/elpy-profile.el#L31) with some alternatives, and also document these in `ide.rst`  Kcachegrind is the heavyweight I've excluded, because I'm guessing only a small subset of Elpy users will have access to it.

https://pypi.org/project/profile-viewer  http://www.vrplumber.com/programming/runsnakerun/
https://github.com/nvdv/vprof
https://github.com/ymichael/cprofilev
http://code.google.com/p/pythontracer

**Comment by galaunay** [comment] 2019-08-27 17:37
Hi,

I choose snakeviz as default because it is easy to use and it doesn't have too many dependencies.
The problem is all the visualisers don't exactly work in the same way (some generate the profile data by themselves, some need it as argument).
Which is why it is not straightforward to integrate all of them.

For now, I added runsnake and pyprof2calltree to the list (because they work like snakeviz and are straightforward to use).
Adding the other ones will need a bit more work...

**Comment by galaunay** [comment] 2019-09-05 10:28
I just merged it to master.

> still haven't achieved the goal of "fully functional Elpy with a one line install command"

Is there any profile visualizer in Debian repos that could be used as a replacement ?

> It looks like I'll have to package both pyprof2calltree and snakeviz!

That's how never ending journeys start :)

**Closed by galaunay** 2019-09-05 10:28 UTC
