### ISSUE TITLE
When the autocompletion fails I get this message:<t> is undefined

### ISSUE THREAD

**Issue by vds** [jorgenschaefer/elpy#1299] opened 2018-02-15 14:55 UTC
After finishing typing a word that the auto completion fails to complete, I get an alert, this is the message: \<t\> is undefined. I'm using GNU Emacs 25.3.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) elpy 20180210.1445

**Comment by mambolevis** [comment] 2018-02-15 17:51
Hi, 
I also observed this behaviour but using company in C++. I don't know if it is related. 
`<t> is undefined`
I am using windows 10.

**Comment by gopar** [comment] 2018-02-15 18:03
Hey all, yeah I've observed this behavior as well. I think it's related to company since after reverting to old versions of a couple of packages including company and elpy , and then only upgrading elpy. Everything seems to work. I didn't really dig too much into the issue. I'll try and see if it actually is company mode

**Comment by mambolevis** [comment] 2018-02-15 19:08
@gopar 
Which version of company do you have? The one without problems.

**Comment by dgutov** [comment] 2018-02-17 16:52
Hi all. I have to ask: does anybody have this problem (seeing `<t> in undefined`) who doesn't use Spacemacs?

**Comment by vds** [comment] 2018-02-17 16:59
@dgutov I don't use Spacemacs.

**Comment by dgutov** [comment] 2018-02-17 17:04
Thanks. That's valuable. Any chance you can provide a step-by-step reproduction scenario in https://github.com/company-mode/company-mode/issues/760#issuecomment-366450480, starting with `emacs -Q`?

Please update company to the latest version before you start, though.

**Comment by vds** [comment] 2018-02-17 17:14
I updated elpy and company and I can't reproduce the error anymore.

**Comment by gopar** [comment] 2018-02-17 19:06
Looks like this was solved in  newest company. Closing this

**Closed by gopar** 2018-02-17 19:06 UTC

**Comment by gopar** [comment] 2018-02-19 19:41
Sadly, issue is not resolved in company. Please see company-mode/company-mode#760

**Comment by mambolevis** [comment] 2018-02-19 22:42
In my case the problem in C++ was solved. 
My emacs version is `GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-24`

Yes, according to the discussion still open in company-mode/company-mode#760 , the problem is more complex than my specific C++ requirement. In python (elpy) I have not seen that behaviour.

**Comment by dgutov** [comment] 2018-02-21 16:17
Should be solved now, with the latest update in MELPA.

**Comment by mambolevis** [comment] 2018-02-21 22:48
@dgutov 
Thank you, I have been following  both discussions from elpy and company. I really appreciate your commitment and engagement.
