### ISSUE TITLE
Jedi: UnicodeDecodeError in sys_path.py

### ISSUE THREAD

**Issue by pallix** [jorgenschaefer/elpy#714] opened 2015-11-16 10:02 UTC
I encounter regularly bugs with my current setup when typing Python code. Here the bug report generated by elpy:

Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

'utf-8' codec can't decode byte 0xb1 in position 25: invalid start byte

Configuration

Virtualenv........: None
RPC Python........: 3.5.0 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/home/user/.local/bin/flake8)

Traceback

Traceback (most recent call last):
File "/home/user/.emacs.d/elpa/elpy-20151101.401/elpy/rpc.py", line 100, in handle_request
result = method(*params)
File "/home/user/.emacs.d/elpa/elpy-20151101.401/elpy/server.py", line 94, in rpc_get_completions
get_source(source), offset)
File "/home/user/.emacs.d/elpa/elpy-20151101.401/elpy/server.py", line 49, in _call_backend
return meth(*args, **kwargs)
File "/home/user/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 45, in rpc_get_completions
for proposal in proposals]
File "/home/user/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 45, in <listcomp>
for proposal in proposals]
File "/home/user/.local/lib/python3.5/site-packages/jedi/api/classes.py", line 470, in type
followed = self.follow_definition()
File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
rv = function(obj, *args, **kwargs)
File "/home/user/.local/lib/python3.5/site-packages/jedi/api/classes.py", line 498, in follow_definition
defs = self._follow_statements_imports()
File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
rv = function(obj, *args, **kwargs)
File "/home/user/.local/lib/python3.5/site-packages/jedi/api/classes.py", line 485, in _follow_statements_imports
return i.follow()
File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
rv = function(obj, *args, **kwargs)
File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 94, in follow
types = importer.follow()
File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
rv = function(obj, *args, **kwargs)
File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 252, in follow
return self._do_import(self.import_path, self.sys_path_with_modifications())
File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
rv = function(obj, *args, **kwargs)
File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 231, in sys_path_with_modifications
sys_path_mod = list(sys_path.sys_path_with_modifications(self._evaluator, self.module))
File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
rv = function(obj, *args, **kwargs)
File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/sys_path.py", line 161, in sys_path_with_modifications
for buildout_script in _get_buildout_scripts(module.path):
File "/home/user/.local/lib/python3.5/site-packages/jedi/evaluate/sys_path.py", line 239, in _get_buildout_scripts
firstline = f.readline()
File "/usr/lib/python3.5/codecs.py", line 321, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 25: invalid start byte
```

**Comment by jorgenschaefer** [comment] 2015-11-16 17:56
Hello, and thank you for the report!

What encoding are you using for your source code files? What are your locale settings?
Do you perchance have an example of one of those files so I can try and reproduce this locally?

**Comment by pallix** [comment] 2015-11-18 09:14
Hello, thanks for the reply.

The file is available here https://github.com/liqd/adhocracy3.mercator/blob/2015-11-pa-add-resources-mercator2/src/adhocracy_mercator/adhocracy_mercator/resources/mercator2.py

I have `LANG=en_GB.utf8`

I think the file is in utf8.

**Comment by jorgenschaefer** [comment] 2015-11-18 18:46
Very strange. Thanks a lot. I'll report this upstream.

**Comment by pallix** [comment] 2015-11-19 09:56
Hum sorry the file is here: https://github.com/liqd/adhocracy3/blob/2015-11-pa-add-resources-mercator2/src/adhocracy_mercator/adhocracy_mercator/sheets/mercator2.py I don't think it matters so much, I have the bug in a lot of different files.

**Comment by mfussenegger** [comment] 2015-12-25 09:55
This is actually caused by the buildout support in jedi. It scans the files inside the `bin/` folder for python files to get the sys.path extensions.

In your case it seems as if the `bin/` folder either contains some binary files or a file which contains non-ascii symbols in the first line.
I've also opened a PR in Jedi to fix this.

**Comment by pallix** [comment] 2016-01-04 09:52
Thanks for looking into this. The `bin` directory of our project contains different files, for instance this one:

```
> head bin/tsc 
#!/usr/bin/env node
require('../lib/tsc.js')
```

Will this be parsed correctly?

**Comment by mfussenegger** [comment] 2016-01-04 20:02
Yes those are fine. As long as there are only characters that are within the ascii range in the first line it's no problem.

I had also tried to reproduce the issue on the repo you linked, but wasn't able to. Maybe you have added some other files into `bin/`?

**Comment by pallix** [comment] 2016-01-05 10:56
Thanks a lot for your research!

Maybe there was a python executable build from the buildout contained in the `python` directory subfolder of the main project at the time I reported the bug.

**Comment by jorgenschaefer** [comment] 2016-01-08 08:18
Thank you, @mfussenegger, for looking into this and your great help! :-)

**Comment by gopar** [comment] 2018-02-11 05:02
Looks like it's solved. Closing

**Closed by gopar** 2018-02-11 05:02 UTC
Labels: Reported upstream, bug
