### ISSUE TITLE
Elpy rpc error timeout bug

### ISSUE THREAD

**Issue by Levomar** [jorgenschaefer/elpy#1405] opened 2018-06-24 12:53 UTC
# Summary
Error Message

```
There's an issue (12 != 9) with the diff parser. Please report:
--- 
+++ 
@@ -3,10 +3,7 @@
 import matplotlib.pyplot as plt
 import serial
 
-
-
-
-
-
-
+class a(object):
+    def __init__(self):
```

# Steps to reproduce

# My configuration

## Debian 9 stretch

Virtualenv........: None
RPC Python........: 3.5.3 (/usr/bin/python3)
Interactive Python: ipython3 (/usr/bin/ipython3)
Emacs.............: 25.1.1
Elpy..............: 1.21.0
Jedi..............: 0.12.0
Rope..............: 0.10.7
Autopep8..........: 1.3.5
Yapf..............: 0.22.0
Black.............: Not found (18.6b4 available)
Syntax checker....: Not found (flake8

## Result of `(elpy-config)`
```
Virtualenv........: None
RPC Python........: 3.5.3 (/usr/bin/python3)
Interactive Python: ipython3 (/usr/bin/ipython3)
Emacs.............: 25.1.1
Elpy..............: 1.21.0
Jedi..............: 0.12.0
Rope..............: 0.10.7
Autopep8..........: 1.3.5
Yapf..............: 0.22.0
Black.............: Not found (18.6b4 available)
Syntax checker....: Not found (flake8
```

## Elpy configuration in my init.el
```
 '(elpy-disable-backend-error-display nil)
 '(elpy-rpc-error-timeout 30)
 '(elpy-rpc-python-command "python3")
 '(elpy-rpc-timeout 30)

```
![screenshot from 2018-06-24 14-51-16](https://user-images.githubusercontent.com/34694536/41819281-1a0f6cb8-77be-11e8-9092-566bdc48a406.png)
![screenshot from 2018-06-24 14-51-24](https://user-images.githubusercontent.com/34694536/41819282-1a289558-77be-11e8-980b-19c81812e3a7.png)

**Comment by galaunay** [comment] 2018-06-24 18:15
What exactly trigger the error, just positioning the cursor at the position shown on your screenshots ?

**Comment by Levomar** [comment] 2018-06-24 18:47
What triggers the error is, the writing of the code, it's not the cursor. once I activate the elpy-mode, and I start writing my code, it doesn't stop showing this error, I tried to change the rpc-error-timeout to stop lugging my emacs, but it didn't work.
Thanks for your help +1:

**Comment by galaunay** [comment] 2018-06-24 22:08
Unfortunately, I couldn't reproduce the error.

Elpy is just informing you of an error that has been raised internally by jedi.
This is likely to be due to a problem in jedi, rather than in elpy.

My first guess would be a corrupted installation, you can try reinstalling `jedi` and `parso` (the library raising the error in the first place).

As a temporary workaround, you can add this at your configuration:
```Elisp 
(setq elpy-disable-backend-error-display nil)
```
Jedi will still fail, but you will not have the annoying popup window.

**Comment by Levomar** [comment] 2018-06-25 07:55
Thank you for help, you were right it was a proble of parso library, it was installed properly using pip, but I don't know why it causes the error. after uninstalling and reinstalling it, emacs doesn't show me the error anymore.
Thanks :+1:

**Comment by galaunay** [comment] 2018-06-25 16:49
I guess that kind of thing just happen sometimes.
Happy to know that it is fixed.

I am closing this issue then.

**Closed by galaunay** 2018-06-25 16:49 UTC
