### ISSUE TITLE
elpy-django not found

### ISSUE THREAD

**Issue by ggiraud** [jorgenschaefer/elpy#1038] opened 2016-12-09 14:39 UTC
Hello,

I cannot install elpy, I get this error message:
`File error: Cannot open load file, No such file or directory, elpy-django`

With --debug-init, i get:
`Debugger entered--Lisp error: (file-error "Cannot open load file" "No such file or directory" "elpy-django")
  require(elpy-django)
  eval-buffer(#<buffer  *load*-168974> nil "/Users/guillaume/.emacs.d/elpa/elpy-20161209.134/elpy.el" nil t)  ; Reading at buffer position 1602
  load-with-code-conversion("/Users/guillaume/.emacs.d/elpa/elpy-20161209.134/elpy.el" "/Users/guillaume/.emacs.d/elpa/elpy-20161209.134/elpy.el" t t)
  require(elpy nil t)
  (not (require (quote elpy) nil (quote t)))
  (if (not (require (quote elpy) nil (quote t))) (ignore (message (format "Cannot load %s" (quote elpy)))))
  eval-buffer(#<buffer  *load*> nil "/Users/guillaume/.emacs.d/init.el" nil t)  ; Reading at buffer position 2556
  load-with-code-conversion("/Users/guillaume/.emacs.d/init.el" "/Users/guillaume/.emacs.d/init.el" t t)
  load("/Users/guillaume/.emacs.d/init" t t)
  #[0 \205\266	\306=\203\30\310Q\202?	\311=\204\30\312Q\202?\313\307\314\315#\203*\316\202?\313\307\314\317#\203>\320\321\322!D\nB\323\202?\316\324\325\324\211#\210
                                                                                                                                                                      \324=\203e\326\327\330\30\331Q!\"\325\324\211#\210
            \324=\203d\210
                          \203\247\332
                                      !\333\232\203\247\334
                                                           !\211\335P\336!\203\201\211\202\214\336!\203\213\202\214\314\262\203\245\337
                                                                                                                                       \"\203\243\340\341
                                                                                                                                                         #\210\342\343!\210\266\f?\205\264\314\325\344\324\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" initialization format-message "`_emacs' init file is deprecated, please use `.emacs'" "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7]()
  command-line()
  normal-top-level()`

**Comment by jorgenschaefer** [comment] 2016-12-09 14:44
Thank you for the report! MELPA unstable has not caught up with the latest changes – I can recommend MELPA stable to avoid such problems. Or you will have to wait a bit until MELPA catches up. :-)

**Comment by arecker** [comment] 2016-12-09 16:23
Same issue here, but I believe I'm on MELPA stable : (

*init.el*

```lisp
(setq package-archives
      '(("melpa" . "https://melpa.org/packages/")
	("org" . "http://orgmode.org/elpa/")
	("gnu" . "https://elpa.gnu.org/packages/")))

(defun recker/package-init ()
  "Initialize the package manager and install use-package"
  (package-initialize)
  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package)))

(recker/package-init)
(org-babel-load-file "~/.emacs.d/README.org")
```

*README.org*

```lisp
(use-package elpy
  :ensure t
  :config (elpy-enable)
  :init (setq elpy-rpc-timeout 10))
```

*WIth `--debug-init`*

```
Debugger entered--Lisp error: (file-error "Cannot open load file" "No such file or directory" "elpy-django")
  require(elpy-django)
  eval-buffer(#<buffer  *load*-96798> nil "/Users/arecker/.emacs.d/elpa/elpy-20161209.134/elpy.el" nil t)  ; Reading at buffer position 1602
  load-with-code-conversion("/Users/arecker/.emacs.d/elpa/elpy-20161209.134/elpy.el" "/Users/arecker/.emacs.d/elpa/elpy-20161209.134/elpy.el" t t)
  require(elpy nil t)
  (not (require (quote elpy) nil (quote t)))
  (if (not (require (quote elpy) nil (quote t))) (ignore (message (format "Cannot load %s" (quote elpy)))) (condition-case err (elpy-enable) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "elpy" ":config" (error-message-string err)) :error)))) t)
  eval-buffer(#<buffer  *load*-36374> nil "/Users/arecker/.emacs.d/README.el" nil t)  ; Reading at buffer position 4031
  load-with-code-conversion("/Users/arecker/.emacs.d/README.el" "/Users/arecker/.emacs.d/README.el" nil nil)
  load("/Users/arecker/.emacs.d/README.el" nil nil t)
  load-file("~/.emacs.d/README.el")
  (progn (load-file exported-file) "Loaded")
  (if compile (progn (byte-compile-file exported-file (quote load)) "Compiled and loaded") (progn (load-file exported-file) "Loaded"))
  (message "%s %s" (if compile (progn (byte-compile-file exported-file (quote load)) "Compiled and loaded") (progn (load-file exported-file) "Loaded")) exported-file)
  (let* ((age (function (lambda (file) (float-time (time-subtract (current-time) (nth 5 ...)))))) (base-name (file-name-sans-extension file)) (exported-file (concat base-name ".el"))) (if (and (file-exists-p exported-file) (> (funcall age file) (funcall age exported-file))) nil (setq exported-file (car (last (org-babel-tangle-file file exported-file "emacs-lisp"))))) (message "%s %s" (if compile (progn (byte-compile-file exported-file (quote load)) "Compiled and loaded") (progn (load-file exported-file) "Loaded")) exported-file))
  org-babel-load-file("~/.emacs.d/README.org")
  eval-buffer(#<buffer  *load*> nil "/Users/arecker/.emacs.d/init.el" nil t)  ; Reading at buffer position 452
  load-with-code-conversion("/Users/arecker/.emacs.d/init.el" "/Users/arecker/.emacs.d/init.el" t t)
  load("/Users/arecker/.emacs.d/init" t t)
  #[0 "\205\266	\306=\203\307\310Q\202?	\311=\204\307\312Q\202?\313\307\314\315#\203*\316\202?\313\307\314\317#\203>\320\321\322!D\nB\323\202?\316\324\325\324\211#\210\324=\203e\326\327\330\307\331Q!\"\325\324\211#\210\324=\203d\210\203\247\332!\333\232\203\247\334!\211\335P\336!\203\201\211\202\214\336!\203\213\202\214\314\262\203\245\337\"\203\243\340\341#\210\342\343!\210\266\f?\205\264\314\325\344\324\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" initialization format-message "`_emacs' init file is deprecated, please use `.emacs'" "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7]()
  command-line()
  normal-top-level()
```

**Comment by arkhan** [comment] 2016-12-09 17:12
try:

(setq package-archives
      '(("elpy" . "https://jorgenschaefer.github.io/packages/")
        ("melpa" . "https://melpa.org/packages/")
	("org" . "http://orgmode.org/elpa/")
	("gnu" . "https://elpa.gnu.org/packages/")))

and

(use-package elpy
  :ensure t
  :pin elpy
  :config (elpy-enable)
  :init (setq elpy-rpc-timeout 10))

**Comment by arecker** [comment] 2016-12-09 17:46
Right from the source.  I like it.  This is certainly a good enough
plugin to earn it's own package archive.  Thanks!

**Comment by jorgenschaefer** [comment] 2016-12-09 19:14
MELPA stable should not build with elpy-django just yet. Strange.

MELPA merged the recipe change, and I just pushed a commit, so this should be fixed with the next MELPA build run (version 20161209191150 something).

**Comment by arecker** [comment] 2016-12-09 19:34
@jorgenschaefer it turns out I wasn't on stable.  I didn't realize that
"stable" had its own subdomain off of melpa.org.

I just pinned elpy to your own repo as suggested by @arkhan.

**Comment by arkhan** [comment] 2016-12-09 21:34
``` elisp
("melpa-stable" . "http://stable.melpa.org/packages/")

(use-package elpy
  :ensure t
  :pin melpa-stable
  :config (elpy-enable)
  :init (setq elpy-rpc-timeout 10))
```

**Comment by gopar** [comment] 2016-12-10 00:52
Looks like the issue is resolved. Anyone still having problems?

**Comment by yogin25** [comment] 2016-12-11 13:30
I still had this issue

When i tried to install it i got this error message:

elpy-django.el:27:1:Error: Cannot open load file: No such file or directory, s

and the line 27 is:

(require 's)

i am using emacs 25.1.1
and i tried to install it from melpa

**Comment by amelio-vazquez-reina** [comment] 2016-12-11 18:33
Same problem here, the one that @yogin25 just reported.

**Comment by amelio-vazquez-reina** [comment] 2016-12-11 18:43
For reference, I am using the latest version pushed on December 9th from `elpy` directly, also on 25.1.1:

```
Debugger entered--Lisp error: (file-error "Cannot open load file" "No such file or directory" "s")
  require(s)
  eval-buffer(#<buffer  *load*-311007> nil "/Users/amelio/.emacs.d/elpa/elpy-20161209.1111/elpy-django.el" nil t)  ; Reading at buffer position 944
  load-with-code-conversion("/Users/amelio/.emacs.d/elpa/elpy-20161209.1111/elpy-django.el" "/Users/amelio/.emacs.d/elpa/elpy-20161209.1111/elpy-django.el" nil t)
  require(elpy-django)
  eval-buffer(#<buffer  *load*-642727> nil "/Users/amelio/.emacs.d/elpa/elpy-20161209.1111/elpy.el" nil t)  ; Reading at buffer position 1602
  load-with-code-conversion("/Users/amelio/.emacs.d/elpa/elpy-20161209.1111/elpy.el" "/Users/amelio/.emacs.d/elpa/elpy-20161209.1111/elpy.el" nil t)
  (elpy-enable)
```

**Comment by jorgenschaefer** [comment] 2016-12-11 18:46
Pushed another commit (with dependency fixes) to master. Let's see if that does it.

**Comment by amelio-vazquez-reina** [comment] 2016-12-11 18:47
Thanks! @jorgenschaefer . I currently only see these versions, but I'll wait for a bit:
```
  elpy      1.13.0        available  elpy         Emacs Python Development Environment
  elpy      20161209.1111 available  melpa-stable Emacs Python Development Environment
  elpy      20161209.1111 available  melpa        Emacs Python Development Environment
```

**Comment by jorgenschaefer** [comment] 2016-12-11 18:57
MELPA unstable can take quite a while (hours) to rebuild new commits.

The version number for melpa-stable looks wrong, incidentally. It should be 1.13.0.

**Comment by gopar** [comment] 2016-12-12 02:17
Hmm why didn't travisCI get any of the errors?

**Comment by amelio-vazquez-reina** [comment] 2016-12-12 02:56
Thank you. That fixed the problem for me @jorgenschaefer All set here!

**Comment by jorgenschaefer** [comment] 2016-12-12 10:45
@gopar Because Travis does not build the package the way MELPA does, nor does it install the resulting package and try it out. The former would be rather tricky to do in CI, sadly.

And thanks everyone, closing this issue then. Please do not hesitate to open a new one if there are further problems!

**Closed by jorgenschaefer** 2016-12-12 10:45 UTC
Labels: bug

**Comment by renatocan** [comment] 2016-12-23 18:56
I'm having the same issue trying to install using el-get (https://github.com/dimitri/el-get)
I think it installs the github version of elpy but I'm still getting "No such file or directory, s"

Thanks!

**Comment by jorgenschaefer** [comment] 2016-12-25 22:28
el-get is not an officially supported method of installing Elpy. Please raise the issue with whoever is maintaining whatever el-get is using to install Elpy, thanks!

**Comment by renatocan** [comment] 2016-12-25 23:32
Ok, I'll open an issue at el-get repository.

Thank you!

Renato
