### ISSUE TITLE
elpy-profile with ipython fails to run

### ISSUE THREAD

**Issue by MRFaria** [jorgenschaefer/elpy#1114] opened 2017-04-05 18:27 UTC
Running 
`M-x: elpy-profile-buffer-or-region `

fails when the emacs python interpreter is set to ipython. 

I had a brief look in elpy-profile.el and it looks the issue arises because ipython doesn't have the "-o" command line option to write the python output to a file.
`(proc-cmd (list python-shell-interpreter "-m" "cProfile" "-o" prof-file file))`

Here is my elpy config:

```
(setq python-shell-interpreter "ipython")
(setq python-shell-interpreter-args "-i")
(elpy-enable)
(setq elpy-rpc-backend "jedi")
(elpy-use-ipython "ipython")
```
My elpy version 1-14-1
edit: I am running ipython version 4.2 because of other issues I had with the newer versions

**Comment by jorgenschaefer** [comment] 2017-04-14 10:12
Hello, and thanks for the report! I suspect elpy-profile.el should use its own variable for the command …

**Comment by memeplex** [comment] 2018-11-28 05:32
Same problem here. It's not difficult to workaround using an advice, though.

**Comment by galaunay** [comment] 2018-11-30 23:44
@jorgenschaefer Do you think it would be a possible to use `elpy-rpc-python-command` instead of having a new option to set ?

**Comment by jorgenschaefer** [comment] 2018-12-14 22:37
Yeah, that looks sensible considering it uses the `-m`argument.

**Comment by galaunay** [comment] 2019-01-30 20:41
Should be fixed by #1528.
I am closing this.

Please re-open if the issue is still happening.

**Closed by galaunay** 2019-01-30 20:41 UTC
Labels: bug
