### ISSUE TITLE
matplotlib figure window "not responding" in Windows 7, no plot

### ISSUE THREAD

**Issue by dstrozzi** [jorgenschaefer/elpy#1152] opened 2017-07-09 19:28 UTC
I am still trying to get a good setup to do scientific python on windows 7.  To be complete, I am using Anaconda for Python package mgmt, and emacs 25.2 (the native windows build from GNU, not the cygwin build).  My goal is to use elpy, with ipython as the Python shell.  The problem I'm hitting is with figure window (big surprise).

I have found some similar issues reported before, but the solutions don't work for me.  In paricular, my init.el has (elpy-enable) and (elpy-use-ipython).

So elpy and ipython work fine, until I do figure(1).  I get a figure window, control is back at the ipython prompt, but the fig window says "not responding."  And if I plot something it doesn't appear.  Various attempts to use ion() and show() haven't worked.

Any thoughts?
Thanks!

**Comment by jorgenschaefer** [comment] 2017-07-14 16:28
Hello, and thanks for the report. I'm afraid I do not use Windows (nor ipython or matplotlib, really), so I have no idea what's going on there :-(

**Comment by dstrozzi** [comment] 2017-08-19 16:43
I'd like to revisit this issue.  But I can't find anything helpful.  I also don't know how to debug this.  Very frustrating!  I am happy to be a guinea pig and try things if someone tells me what to do.

**Comment by jorgenschaefer** [comment] 2017-08-26 14:57
Does this work outside of Emacs?
Does this work with Elpy disabled, just setting `python-shell-interpreter` and `python-shell-interpreter-args` and then using `M-x run-python`?
Does this work with ipython in `M-x shell`?

**Comment by rgemulla** [comment] 2017-09-28 09:30
I am using ```jupyter console``` instead of ```ipython``` on Windows (also with Anaconda). In this setup, matplotlib works flawlessly with ```elpy```.

**Comment by dstrozzi** [comment] 2017-10-13 15:09
Hi,

Sorry it took so long to reply.  I haven't tried this yet.  How *exactly*
do you try this?  Meaning, "edit your .emacs to remove elpy's ipython
whatever and replace it with Y."  Sorry I'm not on my work computer now so
can't see what I do to activate ipython.

Dave

**Comment by jorgenschaefer** [comment] 2017-10-15 12:42
… what do you mean with "this", exactly?

**Comment by rgemulla** [comment] 2017-10-16 06:50
@dstrozzi: Sorry, did not see your message. Here is what I use:

```lisp
;; Initialize Anaconda home directory, workon directory, and default venv
(defun rgmacs/try-initialize-anaconda (anaconda-home)
  (when (file-directory-p anaconda-home)
    (add-to-list 'exec-path anaconda-home)
    (when (file-directory-p (concat anaconda-home "/envs"))
      (setenv "WORKON_HOME" (concat anaconda-home "/envs")))
    ;; uncomment to select a default environment (here: py35)
    ;; (when (member "py35" (pyvenv-virtualenv-list))
    ;;   (pyvenv-workon "py35"))
    ))

;; setup python
(when (string-equal system-type "windows-nt")
  (setq python-shell-completion-native-enable nil)
  (rgmacs/try-initialize-anaconda
   (concat (replace-regexp-in-string (regexp-quote "\\") "/" (getenv "USERPROFILE"))
           "/Anaconda3"))
  (rgmacs/try-initialize-anaconda
   (concat (replace-regexp-in-string (regexp-quote "\\") "/" (getenv "USERPROFILE"))
           "/AppData/Local/conda/conda")))

;; select Jupyter or ipython
(setenv "IPY_TEST_SIMPLE_PROMPT" "1")
(defun rgmacs/set-shell-interpreter ()
  (cond
   ((and (string-equal system-type "windows-nt")
         (executable-find "jupyter"))
    (setq python-shell-interpreter "jupyter"
          python-shell-interpreter-args "console --simple-prompt"))
   ((executable-find "ipython")
    (setq python-shell-interpreter "ipython"
          python-shell-interpreter-args "--simple-prompt"))
   (t
    (setq python-shell-interpreter "python"
          python-shell-interpreter-args ""))))
(add-hook 'pyvenv-post-activate-hooks 'rgmacs/set-shell-interpreter t)
(rgmacs/set-shell-interpreter)
```

The following script works as intended:
```python
%matplotlib
import matplotlib.pylab as plt
plt.figure()
plt.plot(range(100))
```

**Comment by rgemulla** [comment] 2017-12-06 17:02
@dstrozzi Is this still open? If so, I suggest to proceed as @jorgenschaefer suggested:

Does this work outside of Emacs?
Does this work with Elpy disabled, just setting python-shell-interpreter and python-shell-interpreter-args and then using M-x run-python?
Does this work with ipython in M-x shell?

**Comment by dstrozzi** [comment] 2017-12-08 17:44
Hi,

Sorry, I basically gave up on this and decided it's hopeless / too hard to
sort out.  "It" = ipython + matplotlib certainly work outside emacs - from
a command prompt, Spyder, etc.  Also it is *not* an elpy problem, plain
python mode in emacs causes the same issue.

Also it does *not* work from M-x shell + ipython.  Recall I am running
GNU's win32 emacs build, so M-x shell starts a good-old DOS-style command
prompt (not a bash shell).  I do ipython, pylab, figure(1) displays a
figure, the ipython prompt has control again, but the figure says not
responding.  If I try plotting, it doesn't display.  Even with show() or
ion().

Changing the matplotlib backend changes exactly what goes wrong, but in the
ones I've tried something does indeed always go wrong.  It probably has to
do with how python's event loop is being handled.  I don't want to learn
enough about these things to fix it myself, though I'm happy to try things
others suggest.

Dave

**Comment by rgemulla** [comment] 2017-12-08 18:53
I am closing this issue because it is not an elpy problem. 

I do not know what's going wrong here. I am running Emacs on Windows as well (a 64bit build), without any issues. I use Anaconda, jupyter console (instead of ipython) in the setup given above, with matplotlib backend ```Qt5Agg```, and different Python versions (2.7, 3.5, 3.6).

**Closed by rgemulla** 2017-12-08 18:53 UTC
Labels: bug

**Comment by dstrozzi** [comment] 2017-12-10 17:17
OK, I should have tried your advice a long time ago!  Jupyter console
instead of ipython works perfectly!  With TkAgg or Qt5Agg backends.  With
or without elpy.  Thanks so much for this!

Perhaps this approach could be mentioned in the elpy (or some other emacs +
Python) documentation.

Dave

**Comment by rgemulla** [comment] 2017-12-11 23:04
Glad to hear that! 

I'll add this to the documentation as you suggested (see #1244). In fact, I just tried and stumbled across the same issues that you mentioned when I use ipython instead of jupyter console.
