### ISSUE TITLE
Install elpy by git src

### ISSUE THREAD

**Issue by alextinng** [jorgenschaefer/elpy#1019] opened 2016-11-01 05:24 UTC
I cannot connect to jorgenschaefer, so I download src from https://github.com/jorgenschaefer/elpy/issues/new and try to install elpy from src using command "(add-to-list 'load-path "~/.emacs.d/elpas/elpy")
(elpy-enable)", but emacs showed "cannot find function 'elpy-enable'", do you have some advice?

**Comment by gopar** [comment] 2016-11-01 05:29
Hmm **right** after the command `(add-to-list 'load-path "~/.emacs.d/elpas/elpy")` 
did you type in `(load "elpy")`?

That could be the issue :p

**Comment by alextinng** [comment] 2016-11-01 15:36
Hi Daniel,

Thanks for your prompt response and help, I take your advice and reconfigured my emacs.
Here is my configuration:
(add-to-list 'load-path "~/.emacs.d/lisp/elpy")
(load "elpy")
(elpy-enable)

and here is the message emacs showed:
Debugger entered--Lisp error: (file-error "Cannot open load file" "pyvenv")
  require(pyvenv)
  eval-buffer(#<buffer  *load*-4923> nil "c:/Program Files/emacs/.emacs.d/lisp/elpy/elpy.el" nil t)  ; Reading at buffer position 1585
  load-with-code-conversion("c:/Program Files/emacs/.emacs.d/lisp/elpy/elpy.el" "c:/Program Files/emacs/.emacs.d/lisp/elpy/elpy.el" nil nil)
  load("elpy")
  eval-buffer(#<buffer  *load*-411297> nil "c:/Program Files/emacs/.emacs.d/configuration/plugins/configuration.el" nil t)  ; Reading at buffer position 563
  load-with-code-conversion("c:/Program Files/emacs/.emacs.d/configuration/plugins/configuration.el" "c:/Program Files/emacs/.emacs.d/configuration/plugins/configuration.el" nil nil)
  load("c:/Program Files/emacs/.emacs.d/configuration/plugins/configuration.el" nil nil t)
  load-file("~/.emacs.d/configuration/plugins/configuration.el")
  eval-buffer(#<buffer  *load*-731419> nil "c:/Program Files/emacs/.emacs.d/init.el" nil t)  ; Reading at buffer position 187
  load-with-code-conversion("c:/Program Files/emacs/.emacs.d/init.el" "c:/Program Files/emacs/.emacs.d/init.el" nil nil)
  load("~/.emacs.d/init.el")
  eval-buffer(#<buffer  *load*> nil "c:/Users/aoding/AppData/Roaming/.emacs.d/init.el" nil t)  ; Reading at buffer position 70
  load-with-code-conversion("c:/Users/aoding/AppData/Roaming/.emacs.d/init.el" "c:/Users/aoding/AppData/Roaming/.emacs.d/init.el" t t)
  load("c:/Users/aoding/AppData/Roaming/.emacs.d/init" t t)
  #[0 "\205\262

Seems it doesn’t work, do you have some advice?

Best Regards
Alex

**Comment by gopar** [comment] 2016-11-01 20:17
Since your installing from src, emacs doesn't automatically install the dependencies. As you noticed `pyvenv` is one of those.

The list of all dependencies are here:
https://github.com/jorgenschaefer/elpy/blob/master/Cask#L8-L12

**Comment by alextinng** [comment] 2016-11-02 15:38
Hi Daniel,

This really help a lot, but it's very complex, I took a lot of time to do this.

Thanks
Alex




On 11/2/2016 04:17， Daniel Gopar <notifications@github.com> wrote：

Since your installing from src, emacs doesn't automatically install the dependencies. As you noticed pyvenv is one of those.

The list of all dependencies are here:
https://github.com/jorgenschaefer/elpy/blob/master/Cask#L8-L12

**Comment by gopar** [comment] 2016-11-02 17:58
Hey can I assume the issue is fixed? If it is then we can close the issue \o/

Also, how did you try to connect to elpy? Did you follow the instructions on the README about [Quick Installation](https://github.com/jorgenschaefer/elpy#quick-installation)?

**Comment by alextinng** [comment] 2016-11-02 23:50
Hi Daniel,

The issue is fixed, I have another issue about connecting to elpy, you could check that.

Thanks
Alex
On 11/03/2016 01:58, Daniel Gopar<mailto:notifications@github.com> wrote:

Hey can I assume the issue is fixed? If it is then we can close the issue \o/

Also, how did you try to connect to elpy? Did you follow the instructions on the README about Quick Installation<https://github.com/jorgenschaefer/elpy#quick-installation>?

**Comment by ChillarAnand** [comment] 2016-11-03 05:35
Can you try this? https://github.com/jorgenschaefer/elpy/wiki/FAQ#q-how-do-i-install-development-version-of-elpy

**Comment by alextinng** [comment] 2016-11-03 05:50
Hi Chillar,

Really really thank you, that really help a lot.

Regards
Alex

________________________________
发件人: Chillar Anand <notifications@github.com>
发送时间: 2016年11月3日 5:35:32
收件人: jorgenschaefer/elpy
抄送: alextinng; Author
主题: Re: [jorgenschaefer/elpy] Install elpy by git src (#1019)


Can you try this? https://github.com/jorgenschaefer/elpy/wiki/FAQ#q-how-do-i-install-development-version-of-elpy

―

**Comment by gopar** [comment] 2016-11-03 23:12
Nice! I completely forgot about the FAQ. Well if the issue is resolved, feel free to close the issue.

**Comment by jorgenschaefer** [comment] 2016-11-04 13:37
Thanks everyone for helping with this! :-)

**Closed** 2016-11-04 13:37 UTC
