### ISSUE TITLE
Flymake giving error when switching flymake-mode on in ESS mode

### ISSUE THREAD

**Issue by chongl777** [jorgenschaefer/elpy#611] opened 2015-07-14 03:16 UTC
When I try to turn on flymake-mode in ESS for R code, I got this message

  Flymake: Failed to launch syntax check process '~/bin/rflyamek' with args (test_flymake.r): Searching for program: No such file or directory, ~/bin/rflymake. Flymake will be switched OFF.

I put rflymake under /usr/local/bin/, which is in $PATH. The flymake for R is downloaded from here
https://gist.github.com/crowding/3984881

Here's a screen shot:

![untitled](https://cloud.githubusercontent.com/assets/13325365/8665699/e7b6e96c-29b4-11e5-9feb-8308c83f4efc.png)

**Comment by jorgenschaefer** [comment] 2015-07-15 08:37
Hello, and thank you for the question! The problem is that your flymake configuration for R uses a command that does not exist, apparently. I do not know how Flymake is configured for R, and I do not use R.

Did you perchance report this on the wrong package? Or is there a relation to Elpy that I am missing? :-)

**Comment by gopar** [comment] 2017-12-09 02:34
Closing since this is not related to elpy

**Closed by gopar** 2017-12-09 02:34 UTC
Labels: More Info Needed, question
