### ISSUE TITLE
working on elpy in cygwin.

### ISSUE THREAD

**Issue by omps** [jorgenschaefer/elpy#692] opened 2015-10-14 14:31 UTC
Hi,

I am using elpy for quite some time on linux, but a couple of days back i started using it on emacs with cygwin, the problem is though I am opeing the files, it is throwing me with the below error, any help would be appreciated. thanks.

Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

[Error 3] The system cannot find the path specified: 'C:\\home\\user'

Configuration

Virtualenv........: None
RPC Python........: 2.7.0 (/cygdrive/c/Users/user/localapps/Python27/pythonw)
Interactive Python: /usr/bin/python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.5.0 (Python), 1.7.1 (Emacs Lisp)
Jedi..............: 0.8.1-final0
Rope..............: 0.10.2
Importmagic.......: Not found
Syntax checker....: flake8 (/usr/bin/flake8)

Traceback

Traceback (most recent call last):
  File "C:\Users\user\localapps\Python27\lib\site-packages\elpy\rpc.py", line 100, in handle_request
    result = method(*params)
  File "C:\Users\user\localapps\Python27\lib\site-packages\elpy\server.py", line 65, in rpc_init
    self.backend = ropebackend.RopeBackend(self.project_root)
  File "C:\Users\user\localapps\Python27\lib\site-packages\elpy\ropebackend.py", line 57, in __init__
    **prefs)
  File "C:\Users\user\localapps\Python27\lib\site-packages\rope\base\project.py", line 134, in __init__
    os.mkdir(self._address)
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\home\\user'
```

**Comment by jorgenschaefer** [comment] 2015-10-14 15:36
Hello, and thanks for the report!

It looks like Elpy somehow finds a path named `C:\home\user` somewhere, but that does not exist – any idea where it might get the idea of using that from?

**Comment by omps** [comment] 2015-10-15 07:24
the path does exist but since I am using the emacs-w32.exe from cygwin, the path should be picked as in unix format, but it is picking it as in Windows style.

**Comment by jorgenschaefer** [comment] 2015-10-15 07:37
Ok. The error is from Python, I suspect this is some form of cygwin Python that should also use forward slashes?

Any idea where Elpy would get the path name with backslashes from? What does `M-: (elpy-library-root)` show?

**Comment by omps** [comment] 2015-10-15 08:07
Well, not it looks to have worked fine, i remeber clearning lot of python related lisp settings from my init file.

    "~/"

I tried some normal code in my python file, and it seems to work fine for now.

now my elisp only contain the below

    (package-initialize)
    (elpy-enable)
    (elpy-use-ipython)
    (define-key yas-minor-mode-map (kbd "C-c k") 'yas-expand)
    (define-key global-map (kbd "C-c o") 'iedit-mode)

    ; use IPython
    (setq-default py-shell-name "ipython")
    (setq-default py-which-bufname "IPython")
    ; use the wx backend, for both mayavi and matplotlib
    (setq py-python-command-args
       '("--gui=wx" "--pylab=wx" "-colors" "Linux"))
    (setq py-force-py-shell-name-p t)

    ; switch to the interpreter after executing code
    (setq py-shell-switch-buffers-on-execute-p t)
    (setq py-switch-buffers-on-execute-p t)
    ; don't split windows
    (setq py-split-windows-on-execute-p nil)
    ; try to automagically figure out indentation
    (setq py-smart-indentation t)

   (setq
     python-shell-interpreter "ipython"
     python-shell-interpreter-args ""
     python-shell-prompt-regexp "In \\[[0-9]+\\]: "
     python-shell-prompt-output-regexp "Out\\[[0-9]+\\]: "
     python-shell-completion-setup-code
       "from IPython.core.completerlib import module_completion"
     python-shell-completion-module-string-code
       "';'.join(module_completion('''%s'''))\n"
     python-shell-completion-string-code
       "';'.join(get_ipython().Completer.all_completions('''%s'''))\n")
  
    (setq python-shell-completion-string-code
          "';'.join(__IP.complete('''%s'''))\n"
          python-shell-completion-module-string-code "")
 

    ; use the wx backend, for both mayavi and matplotlib                                                  
    (setq py-python-command-args
      '("--gui=wx" "--pylab=wx" "-colors" "Linux"))
    (setq py-force-py-shell-name-p t)

    ; don't split windows                                                                                 
    (setq py-split-windows-on-execute-p nil)
    ; try to automagically figure out indentation                                                         
    (setq py-smart-indentation t)

**Comment by jorgenschaefer** [comment] 2015-10-15 08:09
Good to hear it works now. It is possible that there was a backslash-escaped path configured somewhere, which then was used by Elpy.

Does that mean the problem is fixed? :-)

**Comment by omps** [comment] 2015-10-15 08:20
Even I am having the same opinion now that there must be some definition related with windows path structure, anfd when I tried to fix the problem yesterday by removing all the unnecessary python related lisp code from my emacs, but somehow failed to cross check after restarting emacs, once its done today. It looks to work fine. I will surely report if something new pops up.

Thanks for your prompt help.

**Comment by jorgenschaefer** [comment] 2015-10-15 08:22
Great, I will close this, then. And yes, please do not hesitate to open a new issue if you have any further problems. Enjoy Elpy! :-)

**Closed by jorgenschaefer** 2015-10-15 08:22 UTC
Labels: question
