### ISSUE TITLE
Install buttons for ipython and flake8 use the wrong virtualenv

### ISSUE THREAD

**Issue by yoricksijsling** [jorgenschaefer/elpy#1740] opened 2020-01-06 13:05 UTC
# Summary

The `Install ipython` or `Install flake8` buttons install packages in the RPC virtualenv instead of the project virtualenv.

# Steps to reproduce

I started with a fresh RPC virtualenv by first removing `/home/yorick/.emacs.d/elpy/rpc-venv` and letting `elpy-config` generate it.

I used an empty project with a new virtualenv:

```bash
mkdir ~/elpy-bug-repro
cd ~/elpy-bug-repro
python3.7 -m venv elpy-bug-repro-venv
```

I activated the virtual env with `(pyvenv-activate "~/elpy-bug-repro/elpy-bug-repro-venv")`.

When I go to `elpy-config`, it notices that `ipython` and `flake8` are not installed (among other things). When I press `Install ipython`, it succesfully installs the `ipython` in the RPC virtualenv. It's supposed to be installed in the project's virtualenv (`~/elpy-bug-repro/elpy-bug-repro-venv`) though, so afterwards elpy still can't find it. The same thing happens for `flake8`.

**Workaround**

I can manually `pip install ipython` in the project's virtualenv, then elpy is able to use it.

# My configuration
## OS
Ubuntu 18.04

## Result of `(elpy-config)`
```
Elpy Configuration

Emacs.............: 25.3.2
Elpy..............: 1.32.0
Virtualenv........: elpy-bug-repro-venv (/home/yorick/elpy-bug-repro/elpy-bug-repro-venv)
Interactive Python: ipython (not found)
RPC virtualenv....: rpc-venv (/home/yorick/.emacs.d/elpy/rpc-venv)
 Python...........: python3.7 3.7.5 (/home/yorick/.emacs.d/elpy/rpc-venv/bin/python3.7)
 Jedi.............: 0.15.2
 Rope.............: 0.14.0
 Autopep8.........: Not found (1.4.4 available)
 Yapf.............: Not found (0.29.0 available)
 Black............: 19.10b0
Syntax checker....: Not found (flake8)

Warnings

The python interactive interpreter (ipython) is not installed on the current virtualenv
(/home/yorick/elpy-bug-repro/elpy-bug-repro-venv/). The system binary (nil) will be used instead.

[Install ipython]

The autopep8 package is not available. Commands using this will not work.

[Install autopep8]

The yapf package is not available. Commands using this will not work.

[Install yapf]

The configured syntax checker could not be found. Elpy uses this program to provide syntax checks of
your programs, so you might want to install one. Elpy by default uses flake8.

[Install flake8]
```

## Elpy configuration in my init.el
```
(elpy-enable)
(add-hook 'elpy-mode-hook 'flycheck-mode)
(setq elpy-rpc-backend "jedi")
(setq elpy-rpc-python-command "python3.7")  ;; Black doesn't work with python2.7
(setq elpy-rpc-timeout 3)  ;; Timeout for black reformatting needs to be more than 1 second
(setq pyvenv-mode nil)
;; https://elpy.readthedocs.io/en/latest/ide.html#interpreter-setup
(setq python-shell-interpreter "ipython")
(setq python-shell-interpreter-args "-i --simple-prompt")
```

I also have some magic to switch virtualenv's automatically based on the current project ([here](https://github.com/yoricksijsling/dotfiles/blob/master/emacs/python.el)), but I'm pretty sure it's not related.

**Comment by yoricksijsling** [comment] 2020-01-06 13:25
By the way, I wanted to say thanks for the great work on elpy. It's a really nice integrated experience, and usually works exactly as I want it to :+1:.

---

It looks like the issue here is that all install buttons use `elpy-insert--pip-button`:

https://github.com/jorgenschaefer/elpy/blob/c7c252dcc73bf817c3b67349720f8e1b29be1277/elpy.el#L973

The widget assumes that the RPC virtualenv needs to be used, both in `elpy-insert--pip-button-value-create` and `elpy-insert--pip-button-action`:

https://github.com/jorgenschaefer/elpy/blob/c7c252dcc73bf817c3b67349720f8e1b29be1277/elpy.el#L1253-L1289

**Comment by galaunay** [comment] 2020-01-12 16:47
Thanks for getting to the bottom of it !
I made PR #1745 to address this.
Should be merged tonight.

**Comment by ursetto** [comment] 2020-01-21 21:56
I'm curious why it doesn't just install in the RPC venv, and fall back to that if it's not in the current venv. The problem is, if you already have a flake8 installed anywhere in your path -- even for a different python version -- elpy will find that one. Therefore it doesn't even pop up the button to install a version in your current venv. That feels a bit strange, as elpy takes great pains otherwise to confine its dependencies to a venv; it makes switching between Python 2 and 3 harder.

**Comment by galaunay** [comment] 2020-02-02 20:37
I agree that flake8 should be installed in the rpc virtualenv and used from there.
There was already another comment regarding this.

I will have try as soon as I can.

I am closing this in the meantime, feel free to reopen if needed.

**Closed by galaunay** 2020-02-02 20:37 UTC
Labels: Bug
